// <auto-generated />
using System;
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCapitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250804100148_newDb")]
    partial class newDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2a561aab-d12b-4391-9132-f7da67125396",
                            ConcurrencyStamp = "2771987f-1f18-4308-a5bf-e05dfbc90a69",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEP+k+gHYdDb+iPFpkt5azFsDpfmGvX/vK151e0ztvf7NAoL3bNY6SLRPvJovFoZhPg==",
                            SecurityStamp = "755a5993-af47-4f85-961a-0303c2b4038f",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "d2e4957d-cef0-4062-a6c9-3f588f13f58f",
                            ConcurrencyStamp = "ac918798-6fad-4d4b-a2e9-25327d4d300b",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEJpHdlo01Hr7JwMOIQ8Oj3z4bBBKasgmSKt7/5ZmwZYcwAq7XU9eT9BqQBNE5HHbVg==",
                            SecurityStamp = "7ab6bbf3-0768-430d-bac6-27c03b288a85",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "6951b2ae-f6f4-4da5-9136-b25004c28f9c",
                            ConcurrencyStamp = "cc988eaf-c0f2-44fb-bdad-22218dce8429",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEJGcvtmE+t2W9irvShNKyB4oB++MVl33hmop07StGxewq7tmf4/jnOLYp/3XiE872g==",
                            SecurityStamp = "210e184e-895a-431c-b694-59829a130a4d",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "0b2c6feb-b642-49f8-84ef-680d3ff2c344",
                            ConcurrencyStamp = "1f266754-9c4e-41d8-b6c4-1ff462ef71ab",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEB4197R7o4wvQF11B1c/SwXW4KpeT+SjWaY0yryf9OaABwBMldGEQgslrcIG1Fw8cA==",
                            SecurityStamp = "b7599c58-1cae-4019-b115-8772a7c23989",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "726d58c1-73fa-43fb-b3fb-48ec29b2ac5c",
                            ConcurrencyStamp = "d9684abf-1e50-482c-9a41-f75e93efe822",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEPaCSMzZo/lxHTp5Sr3hgybojTFktI5Ccn6ehg3n362SOEnhyuZO0NZa0WcagQ36VA==",
                            SecurityStamp = "a56ae11d-07f8-4093-9099-35828ce115c5",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "f7afdc1e-c904-44e2-9224-43e4aecbc673",
                            ConcurrencyStamp = "ffc48d3a-988a-4907-a723-116283d37018",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAEOzs+RDXXW7oHcpVrt2Gqno8sOUVZN0I6GClIJF+n6jjpnUGjaUTzVyM6lh4sX0NNw==",
                            SecurityStamp = "05d926bd-66ea-47ff-892d-57c14c0c602f",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "e2a94c68-334a-4305-b96b-46693e124d1b",
                            ConcurrencyStamp = "a7e67950-1c95-4a32-b5fe-1211307c98f0",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAELOdIV/MpydcozYco8xh+6AKzHn0MEmfAQCDVnfJfEgBP0S58kz/Zk1o+m+HrRYYsw==",
                            SecurityStamp = "8f896a87-1ff9-420d-87ee-986681dd878d",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "8e0bcaef-52af-4021-b2f3-1f2770d38d52",
                            ConcurrencyStamp = "bbfd9792-6748-4ba9-8d0c-56a3ef0944c8",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAEKFHGoq/OBkq+NSx/be4MD8OLZeFUHq7agzNL2qjvcSBuzbk1omjYBJUt9VhAaRTjg==",
                            SecurityStamp = "4804527f-8faa-4c1e-8285-f3d729fad26f",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "c5c20525-4a8f-4a6f-bd5f-70cafc974b97",
                            ConcurrencyStamp = "b44c5178-c1fa-444e-9761-456aee1020fc",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEHJAt2/YhFskGPGnVYf1YEBlE8fCSJwWH7vDFzt36nAyo/eoWk+gwYlgPsIiTWhOLw==",
                            SecurityStamp = "6a260fa4-83ac-4e1c-b527-24aa63241b27",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "7da74fd5-160f-4cd6-91b2-8628f4f47a83",
                            ConcurrencyStamp = "17f66d17-b8fa-49b1-9865-ab2b600c3aa4",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEB8lLRu95dWH3zRuyUgUYWJNqXOcIQi/ouQL5/KPVidgu/xaIXWjh4fEc7HimECe5Q==",
                            SecurityStamp = "edf319de-412d-4078-974d-517b7a6418b4",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "4eaa9c9e-8590-4534-960b-4c72ec5de01b",
                            ConcurrencyStamp = "60831237-0670-4696-a762-b2bd81d9224e",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAENEfp2d4INy7FudNFhYQvkfX3Qzoe4wJ4S82cf/lQ9CmRkbXUA23Wuv61q4lozFwLw==",
                            SecurityStamp = "f06b7d07-8968-4918-938a-b65ac826de25",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "7dd20390-ce34-4e8a-9989-7861830cb12d",
                            ConcurrencyStamp = "7721debb-2a4d-4f0c-a47c-ab694827dfd8",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAEM4RaF/ea6o5nNkVklQkSs1jR41AjTDHzGIVIhkBk3zN+rmjDXXaaCTq6eGm6kmlZQ==",
                            SecurityStamp = "3e571394-622c-4207-a7aa-2deb97bdf33d",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "5b2bc7e2-8f2c-43c5-9027-99b354272660",
                            ConcurrencyStamp = "31ea420d-64cd-4ed9-9028-c3c5e1200818",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEAcbdT1Rqtb+oyORu4ubnRLhMpRgwCgBFKcnvogRMhH+fVddooW+MvHzgLV9Z9/CRQ==",
                            SecurityStamp = "739d364a-5481-42f7-afbe-703276b9d02f",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "6096bf5f-c034-4c83-91d5-f911cbe361ea",
                            ConcurrencyStamp = "eb6f5b8b-595e-46bf-b9f7-dab6a5309a0e",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAEJoZoQOqAF9JeHziiiICMgj+nCB3YV2HBnTBWQH5lD3QlsL9XimBkh+rYpOkKwaDow==",
                            SecurityStamp = "37339ac0-1e71-4602-953b-bad2d522bc97",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "52404cf1-e1de-4159-a6c7-206d7eb1782a",
                            ConcurrencyStamp = "a98bbe52-3741-4c69-8c4f-7fd96eb695ba",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAEHLuODXReu/xxFnrPEv7EBqOracfVUQU5PfVoJb2WOva7CVr5X/bA70SOU1LgvPV+g==",
                            SecurityStamp = "c8e61b9e-266d-46fc-9dfd-5cdf01f490ed",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "06ab1e2f-9194-447b-9847-70297d410585",
                            ConcurrencyStamp = "1edcdf3c-e58f-4769-8067-e832b592cb7a",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAEM6zI5LnE0L7zYLmBL+CPSVAWa/e6CfA4KrKQ/NdVvq/8mMoYBYqmK1H0NdWVdBVKQ==",
                            SecurityStamp = "f16d6df4-0b86-451a-a22a-2ed6815032a7",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "d16589d3-e5e3-4c10-a858-c37d115d10ba",
                            ConcurrencyStamp = "ebd75135-4fe7-4c57-90d7-aac5f5a8249d",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAEFVkDjQx/8NUDtLQdvrbQxo2xG7UN/j99cDKs+GadSQ/5gZEoXel/wvWfRaeB9YFqw==",
                            SecurityStamp = "2159fa7b-40c6-44a8-940b-3e98835c576e",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "5328b4b2-c307-4932-8547-57857a70b30c",
                            ConcurrencyStamp = "a8c1ee24-1c93-40ca-888a-a27d7bdcbf58",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAEIiFmpbrz68XTR3Lj2+QeaiYwRLOsjtqcyjiCSozCDA50tiEEIpEzTXwqjmxm8cWRQ==",
                            SecurityStamp = "44338f50-9562-4462-a3e5-b23d1c9370ff",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "4b00f983-a2b3-4366-955b-85d1fa2ae6fb",
                            ConcurrencyStamp = "11971ecd-fde4-43ed-877d-3c050cd67483",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAEHS4plJ3y7qxD8SZcZlE10pjP7zwLtbisVZ3T7DNJyj0koTQYkOsP4dDnZ2hbbsY8g==",
                            SecurityStamp = "2aae78c9-e55b-477b-a42b-675948789147",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "bbfed021-45ee-40a5-97b8-a2ac21c6d198",
                            ConcurrencyStamp = "c9dc8b7f-884e-4f48-b154-2eba3cdda742",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAEIOgvc9zGxDCyBtYf4jhjxVDPmqfj4pfVHr3yadQLu3wfLt6rEV06p5Y2rjdDmWlUw==",
                            SecurityStamp = "f7dbb8c3-9444-493d-968c-a2e95e8eba48",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "ab4fa6d6-d7b7-42da-a023-7b1a8e3d0b91",
                            ConcurrencyStamp = "14915e06-479e-4a41-ba20-faffcce264d8",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAEBlW5WXneo46iAi83fcpQs8wWPgdT7c6iEYM37wtyMQPJVh0UcNd1Mf+HZOXviTNmQ==",
                            SecurityStamp = "d85d546b-48d3-4f8b-84e7-2cb936ba36c2",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "1023b4e0-446e-460b-8f95-aa88c57c26df",
                            ConcurrencyStamp = "fcb02027-aaaf-470b-88e5-ce996e8b164f",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAEFegaNSeKWEl0yugpiw8E8qGOs6tA/2RlHqOLEUllA/MR64fRpL6/LUTZIi6JeAmJQ==",
                            SecurityStamp = "58afc918-5ed9-43cf-b164-92feceb6cfca",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "e871640c-a4bd-4299-b669-def9e01d4e67",
                            ConcurrencyStamp = "97f00eb3-571c-4566-9d38-22937245d58f",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEEO42MSEo8Tzh5y7Zm8dzKxKnR4wh7Ro4ZUr/5ARJDGAFZHtz7YzI2iu1wmqpnU5XQ==",
                            SecurityStamp = "3f32edb6-9dc5-4dbe-b75a-352a58423348",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "bd265674-3975-4d45-b2f4-dab47fe760f9",
                            ConcurrencyStamp = "14071c6e-6b7d-4c74-b00b-1034919b15be",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAECZSLcIgmu0y+fC46jjqWbXg0+cDrQooIC+gEWdx01dBOld/wk88ofRRSSaq3iGKPA==",
                            SecurityStamp = "5842d493-32cf-4a16-bb13-35a407f7d2c4",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "a95df43d-3e6d-4291-989a-3aa48063e1ac",
                            ConcurrencyStamp = "cdb19742-0284-4dd1-9310-d31dc85b9fa1",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEBp+BxoDDcOwGzkZczdaMKtHehDlv6Rt6fIJ9K0toyigmQvp3adZ1j4BqnGDfXfYkA==",
                            SecurityStamp = "b5b07cc4-ab92-4bc5-adc2-03b3fddc9801",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "f08881d5-7483-4eea-afc7-a1c402226c06",
                            ConcurrencyStamp = "9f702875-4e1e-4a55-8569-1ba533de3555",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAENbHy+BK9BCE68pYrLEzPUe7hWptDrITDZEK7mkQwoppuZCYHFWPHFG5tyyl4vgpnw==",
                            SecurityStamp = "d6f7230f-a63b-4ac2-b359-dbf187156a63",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "c04d52fb-9fe6-4782-80cc-1867821fce44",
                            ConcurrencyStamp = "eeec70c4-bdbb-467e-ba06-ed8cad3dfae5",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAEGOfDdCpjgLo5kfwYcgWkixuCt8DqIwdeuIjf2hJRLEYCvToNrxbnRMTN/+8fO68QQ==",
                            SecurityStamp = "1bcfbb8a-7bf9-4514-a7c2-654cf21c067e",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "8d51c159-6db7-466f-a48d-9dfecc31c543",
                            ConcurrencyStamp = "00d08295-d24a-4e7c-8f77-45238a181438",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEFtVmZ6WeknmmMUukNZWbN+WQ4dU42blMVofdmZ6RbNWcOyp61qZvx+6JiMJCE5yiQ==",
                            SecurityStamp = "73edaea2-1666-4978-8c6c-fa82e3f766da",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "994946ef-8443-4db5-9369-fe1c871577d1",
                            ConcurrencyStamp = "8bb4b0c5-6f9c-41d5-b5ee-22d79b48ae89",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAEH9rOIYSZfINj0/+a8ZFPFh0M87BtWFyidOA1I5sVLebyBUKXduBWoYoVGzLAOTSXQ==",
                            SecurityStamp = "1c875598-7820-4900-9c4f-0bac50b3b54f",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "fc28eb59-dcf7-46bf-81ff-bd16ef7171d8",
                            ConcurrencyStamp = "16e1af7b-f8cc-45b0-9bcd-804538194340",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAEASEryBPw2B2a9Yz3QPOK65Azew6WEl9SFjWNAK9ZuN75//Nv/jSc9utXdC93XlttA==",
                            SecurityStamp = "48bcf21d-98e7-4f6f-8271-37dee33a10f7",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "661d2c59-4abf-4f5f-b743-98be0e5644a9",
                            ConcurrencyStamp = "80c2b5fe-c713-436b-8c51-fdc73b28f85c",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEBxtAjmyq/LwHxtf7/PWzcicxFB5lTwWopHMXxjTmbhdueUJBf0eEqol+YLvboA0VA==",
                            SecurityStamp = "d5b1972f-5515-4397-a91e-5db9f27ce3e5",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "056a8e45-40e3-4665-ae80-a499e7ed4fd6",
                            ConcurrencyStamp = "bbbf0d28-3ed9-49eb-b36b-b552a8a83bad",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEHEm6a6ICUjLa0FOaDZQcKct14ei8tzpJiZAnLsI05xcCxAV4CcY2Mqse9ITo3h2lw==",
                            SecurityStamp = "7806503e-eb14-4573-8ac6-6e92a69be0fe",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "af77617b-e2b5-4e09-8d9e-85d222d82564",
                            ConcurrencyStamp = "da97d287-f090-4247-be7e-d42a0db98857",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAEInYxHdzZOEvhM4hOFKGCjk4/Ad9YlgsculDW3HDscO5SRps8WTqM7ceX/vSArrQbA==",
                            SecurityStamp = "00dd8066-4269-49bf-b09f-833b74ca3fd2",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "702b60fd-a373-4099-8c5a-5f4bbd869668",
                            ConcurrencyStamp = "0a24bb27-d21e-45b1-bcac-e9dfd4ecba8c",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAECRDPIrLqGwWUqiQgn4AXSFKXflzFlZSzenf8pulbqndXbXnbov6KauDkjB3GRg02w==",
                            SecurityStamp = "6afd7a36-8a51-4d82-aae9-f1c6e5c089ed",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "c16dbd99-0405-4ada-9298-1240a2f3c1b1",
                            ConcurrencyStamp = "36f416a4-9da9-4ff1-a881-9b36cfa4e109",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAECBQcKDlwb+zgvGRpjCkAWyyqINy/fJ/yCcczI0Wc5hZpXSw6EmXGRFC4DvVZbJBsg==",
                            SecurityStamp = "603e3d1f-105a-4f1d-8f62-d4653cc920ac",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "e96bcfb5-e8fe-43e3-8cce-7d34630d395d",
                            ConcurrencyStamp = "329842a2-810a-4876-8383-f1e8d1c8dba0",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAEO2SXaGKuF0WpjtOZpmiqUXRUmQMoTySeKNM6y/kw30Byna9Kb05MJNm880WjmndFg==",
                            SecurityStamp = "4769baf4-e368-493e-820b-55c29ce0b1bb",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "91325d43-de93-49d9-8e08-f48e142a446a",
                            ConcurrencyStamp = "57cc60d9-0342-4d00-a86d-ce119f0c8441",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEAUvzkWMmB5JlDxtr1KE6OvGwd0rcpHP5e2zaaOl+XgIm6gZR4VEgg09og048f7Evw==",
                            SecurityStamp = "1e028e21-47fb-47a5-b03d-005dae0bc57b",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "4bcc0e46-09c7-451d-b3d6-2f7d93ac12ae",
                            ConcurrencyStamp = "bae5881f-13d3-4a5c-bc79-1e0b82a688d2",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAEKlLf7lry//fhPUecbUEHE9uoxvnoFsoJawPgX25Rf06qtGq+UJkBiiF64mgn7DJBA==",
                            SecurityStamp = "45699bd1-67f9-4506-8423-855956d49bbf",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "d31ab548-c3ee-489e-b6f4-6794a39beefc",
                            ConcurrencyStamp = "d2a596c1-044d-45c4-ba72-0a848787f2c1",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ0XplvoRqq0ZYbvoxvnHHZXJoOTrXGVIpEJ4bl67d6vvhzsby53ti98Pg7jqUFcfA==",
                            SecurityStamp = "25545d29-eeec-4a72-9a53-390d65a0b78b",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "6d83b64c-4eea-4f37-83a9-7353d0e957d6",
                            ConcurrencyStamp = "3e740169-c4d5-41bb-9d37-51b5f7592e58",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEKzOYiwM01FMXyR8Cc4T5D50tf2iRwe2ofdV6RxaTHyEQNJYc5Bxx+b9W7flGfvx1A==",
                            SecurityStamp = "1cc15fb5-64e6-445e-94c0-a73df9420fde",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "18eaacb8-e4be-4869-9551-7208c70b7824",
                            ConcurrencyStamp = "f374fccd-4571-4816-9018-d096ef16f917",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAEADkisikfQ9I+AwbI3j7qCGpEYPzYQxAU3qIPybKUxA9SZsEyPnOyGQFnA3qE4zC8g==",
                            SecurityStamp = "3be5c49b-1267-4d4d-8449-137661a4a626",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "9d094fdf-c338-4301-ace7-91d4ca9f7ad0",
                            ConcurrencyStamp = "be106c1c-fbcf-4b13-a774-1616790adeaa",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAECtBw51baECmAea/E5xaZbv+tHHACpQ2apdd5Yqu4BVIkBLw5sskFx4IE81ao7EZ7w==",
                            SecurityStamp = "eb72054a-1582-42d6-8591-fe50f8029fd7",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "c5c8a4a8-5e08-4cb9-a1a8-edc657f42719",
                            ConcurrencyStamp = "d0055d20-129b-4557-84c8-e16cd12a67bc",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAEMKWIGTWzFqp4MClp7dOQZ7WAbSonzL28A5FKH+DyAzKmIq1CrGPq2hbFHg/5Cb/zQ==",
                            SecurityStamp = "c8466d17-bc44-4e3a-9280-f3c4f2fa3bd5",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "729717c6-1ddc-4c09-8117-a254c2d5c263",
                            ConcurrencyStamp = "f9522e3c-0be2-4ff7-85c1-fbc317e992a6",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAEKnrZ3TJ1xjvjKxHfzDUyD1Tdhv4/IJcuCMOWmxkd5QL/FNNsIUTur9u08tIYvNuuQ==",
                            SecurityStamp = "a77d9619-9e69-416d-81fb-5be2057a3842",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "a416fab3-37c5-4771-8e73-e37363d4dc2f",
                            ConcurrencyStamp = "d7c0f3c9-f62d-483e-92e6-b157a5d9dc7f",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAEPEjeXsXap0azG+s1hAE7/SeJm4cNUbt/+A48ZIjMtK1hIoGceD96/msvogec8EGhg==",
                            SecurityStamp = "d7c1bb44-aba0-458b-b89a-cd678e0c9bcd",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "10d13800-c4cb-4125-a9de-2baf160b09fc",
                            ConcurrencyStamp = "d5ad9c5c-78c7-42ff-8e90-a20b558122fd",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ61ujdWk/nLuQ+6I22LoV1tlTp+wWymOSksGJGiYmP88qdysFQxQHIKoSXIT9a2Ng==",
                            SecurityStamp = "eb4f1015-40bf-46d7-b200-e8f8ede0ec29",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "df694b56-2105-48bb-a29d-977166995cd4",
                            ConcurrencyStamp = "f53f0d32-61ab-4b8e-a288-8015a5575aec",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAENBFfRB8T4zhBmNG4GkxrWiYrw7d2Zw8ooT/0Wi8zW2BMI05mh7WtHxNm4VioJPAYg==",
                            SecurityStamp = "e465e6b1-5ed6-4802-b7a1-844c9f3a4a85",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "10f6c8e2-b8ee-489b-a654-b3c96faec0e7",
                            ConcurrencyStamp = "c383ca9c-af76-4f7e-b266-85acda8e1b07",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAEMrWFAaAOCyKbaywVYuzo579ipTPwd+HgWVlevffZ2SoutFXedFDELTQXloq+MCkLQ==",
                            SecurityStamp = "9866083b-5e07-4d4a-8b0d-596a050e1599",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "b6ed985c-13ed-4916-8d38-b5a45cb6665c",
                            ConcurrencyStamp = "21184f8c-7125-44cd-88ac-c01d8058f3d7",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAEKqy4/Hgg1Ga+a3j8qHpGdiQl0p4ZiWypOvQjzad/LPqbGBC02BRahy5ztH7ZxCX2w==",
                            SecurityStamp = "71dd4c45-6bbf-489f-93d9-a4e3b885ef2a",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "7b6b47ee-1bf8-4aae-90fc-4c1e268a1371",
                            ConcurrencyStamp = "fa91a275-5b13-47fc-bc2a-6be25d924808",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEP/tL4dXIMmNOajNBvtuWQ/ReDJeswfOvQigIPuL8mRdSwWnuQEC1Ugp9xyGyInzOg==",
                            SecurityStamp = "63560f12-add6-4e9d-ab89-c4f67690e319",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedIBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "johndoe1@company.gmail",
                            Country = "USA",
                            DepartmentId = 2,
                            EncryptedIBAN = "VVM5N0JPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3036.0m,
                            UserId = "2a561aab-d12b-4391-9132-f7da67125396"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "johndoe2@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 3,
                            EncryptedIBAN = "Qkc2MlVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 6015.0m,
                            UserId = "d2e4957d-cef0-4062-a6c9-3f588f13f58f"
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "johndoe3@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 4,
                            EncryptedIBAN = "QkcxMFVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3144.0m,
                            UserId = "6951b2ae-f6f4-4da5-9136-b25004c28f9c"
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "johndoe4@company.gmail",
                            Country = "USA",
                            DepartmentId = 5,
                            EncryptedIBAN = "VVMyMUJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 3022.5m,
                            UserId = "0b2c6feb-b642-49f8-84ef-680d3ff2c344"
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "johndoe5@company.gmail",
                            Country = "Germany",
                            DepartmentId = 6,
                            EncryptedIBAN = "REUzOTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 4309.5m,
                            UserId = "726d58c1-73fa-43fb-b3fb-48ec29b2ac5c"
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "johndoe6@company.gmail",
                            Country = "UK",
                            DepartmentId = 1,
                            EncryptedIBAN = "R0I3NU5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2610.0m,
                            UserId = "f7afdc1e-c904-44e2-9224-43e4aecbc673"
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "johndoe7@company.gmail",
                            Country = "UK",
                            DepartmentId = 2,
                            EncryptedIBAN = "R0IxMk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2149m,
                            UserId = "e2a94c68-334a-4305-b96b-46693e124d1b"
                        },
                        new
                        {
                            Id = 8,
                            CompanyEmail = "johndoe8@company.gmail",
                            Country = "UK",
                            DepartmentId = 3,
                            EncryptedIBAN = "R0I0Nk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4918m,
                            UserId = "8e0bcaef-52af-4021-b2f3-1f2770d38d52"
                        },
                        new
                        {
                            Id = 9,
                            CompanyEmail = "johndoe9@company.gmail",
                            Country = "France",
                            DepartmentId = 4,
                            EncryptedIBAN = "RlI4OTMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2095m,
                            UserId = "c5c20525-4a8f-4a6f-bd5f-70cafc974b97"
                        },
                        new
                        {
                            Id = 10,
                            CompanyEmail = "johndoe10@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 5,
                            EncryptedIBAN = "Qkc3NlVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 3292m,
                            UserId = "7da74fd5-160f-4cd6-91b2-8628f4f47a83"
                        },
                        new
                        {
                            Id = 11,
                            CompanyEmail = "johndoe11@company.gmail",
                            Country = "Germany",
                            DepartmentId = 6,
                            EncryptedIBAN = "REUzMzM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2911m,
                            UserId = "4eaa9c9e-8590-4534-960b-4c72ec5de01b"
                        },
                        new
                        {
                            Id = 12,
                            CompanyEmail = "johndoe12@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 1,
                            EncryptedIBAN = "Qkc2NFVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1507m,
                            UserId = "7dd20390-ce34-4e8a-9989-7861830cb12d"
                        },
                        new
                        {
                            Id = 13,
                            CompanyEmail = "johndoe13@company.gmail",
                            Country = "France",
                            DepartmentId = 2,
                            EncryptedIBAN = "RlIzNjMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2107m,
                            UserId = "5b2bc7e2-8f2c-43c5-9027-99b354272660"
                        },
                        new
                        {
                            Id = 14,
                            CompanyEmail = "johndoe14@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 3,
                            EncryptedIBAN = "Qkc2NVVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4544m,
                            UserId = "6096bf5f-c034-4c83-91d5-f911cbe361ea"
                        },
                        new
                        {
                            Id = 15,
                            CompanyEmail = "johndoe15@company.gmail",
                            Country = "USA",
                            DepartmentId = 4,
                            EncryptedIBAN = "VVM1MUJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2083m,
                            UserId = "52404cf1-e1de-4159-a6c7-206d7eb1782a"
                        },
                        new
                        {
                            Id = 16,
                            CompanyEmail = "johndoe16@company.gmail",
                            Country = "USA",
                            DepartmentId = 5,
                            EncryptedIBAN = "VVM1NUJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 2213m,
                            UserId = "06ab1e2f-9194-447b-9847-70297d410585"
                        },
                        new
                        {
                            Id = 17,
                            CompanyEmail = "johndoe17@company.gmail",
                            Country = "Germany",
                            DepartmentId = 6,
                            EncryptedIBAN = "REU1NzM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2711m,
                            UserId = "d16589d3-e5e3-4c10-a858-c37d115d10ba"
                        },
                        new
                        {
                            Id = 18,
                            CompanyEmail = "johndoe18@company.gmail",
                            Country = "Germany",
                            DepartmentId = 1,
                            EncryptedIBAN = "REU0NTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1770m,
                            UserId = "5328b4b2-c307-4932-8547-57857a70b30c"
                        },
                        new
                        {
                            Id = 19,
                            CompanyEmail = "johndoe19@company.gmail",
                            Country = "Germany",
                            DepartmentId = 2,
                            EncryptedIBAN = "REU4MTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2159m,
                            UserId = "4b00f983-a2b3-4366-955b-85d1fa2ae6fb"
                        },
                        new
                        {
                            Id = 20,
                            CompanyEmail = "johndoe20@company.gmail",
                            Country = "UK",
                            DepartmentId = 3,
                            EncryptedIBAN = "R0IxOU5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4848m,
                            UserId = "bbfed021-45ee-40a5-97b8-a2ac21c6d198"
                        },
                        new
                        {
                            Id = 21,
                            CompanyEmail = "johndoe21@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 4,
                            EncryptedIBAN = "QkcyMVVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2018m,
                            UserId = "ab4fa6d6-d7b7-42da-a023-7b1a8e3d0b91"
                        },
                        new
                        {
                            Id = 22,
                            CompanyEmail = "johndoe22@company.gmail",
                            Country = "UK",
                            DepartmentId = 5,
                            EncryptedIBAN = "R0IzMk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 2859m,
                            UserId = "1023b4e0-446e-460b-8f95-aa88c57c26df"
                        },
                        new
                        {
                            Id = 23,
                            CompanyEmail = "johndoe23@company.gmail",
                            Country = "Germany",
                            DepartmentId = 6,
                            EncryptedIBAN = "REU0NjM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2622m,
                            UserId = "e871640c-a4bd-4299-b669-def9e01d4e67"
                        },
                        new
                        {
                            Id = 24,
                            CompanyEmail = "johndoe24@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 1,
                            EncryptedIBAN = "Qkc4OVVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1646m,
                            UserId = "bd265674-3975-4d45-b2f4-dab47fe760f9"
                        },
                        new
                        {
                            Id = 25,
                            CompanyEmail = "johndoe25@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 2,
                            EncryptedIBAN = "Qkc3NFVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2095m,
                            UserId = "a95df43d-3e6d-4291-989a-3aa48063e1ac"
                        },
                        new
                        {
                            Id = 26,
                            CompanyEmail = "johndoe26@company.gmail",
                            Country = "UK",
                            DepartmentId = 3,
                            EncryptedIBAN = "R0IzOE5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4348m,
                            UserId = "f08881d5-7483-4eea-afc7-a1c402226c06"
                        },
                        new
                        {
                            Id = 27,
                            CompanyEmail = "johndoe27@company.gmail",
                            Country = "UK",
                            DepartmentId = 4,
                            EncryptedIBAN = "R0I0OU5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2022m,
                            UserId = "c04d52fb-9fe6-4782-80cc-1867821fce44"
                        },
                        new
                        {
                            Id = 28,
                            CompanyEmail = "johndoe28@company.gmail",
                            Country = "Germany",
                            DepartmentId = 5,
                            EncryptedIBAN = "REU2MTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 2032m,
                            UserId = "8d51c159-6db7-466f-a48d-9dfecc31c543"
                        },
                        new
                        {
                            Id = 29,
                            CompanyEmail = "johndoe29@company.gmail",
                            Country = "France",
                            DepartmentId = 6,
                            EncryptedIBAN = "RlI2NDMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2626m,
                            UserId = "994946ef-8443-4db5-9369-fe1c871577d1"
                        },
                        new
                        {
                            Id = 30,
                            CompanyEmail = "johndoe30@company.gmail",
                            Country = "France",
                            DepartmentId = 1,
                            EncryptedIBAN = "RlIyNDMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1713m,
                            UserId = "fc28eb59-dcf7-46bf-81ff-bd16ef7171d8"
                        },
                        new
                        {
                            Id = 31,
                            CompanyEmail = "johndoe31@company.gmail",
                            Country = "USA",
                            DepartmentId = 2,
                            EncryptedIBAN = "VVMxNkJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2052m,
                            UserId = "661d2c59-4abf-4f5f-b743-98be0e5644a9"
                        },
                        new
                        {
                            Id = 32,
                            CompanyEmail = "johndoe32@company.gmail",
                            Country = "Germany",
                            DepartmentId = 3,
                            EncryptedIBAN = "REUzODM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4226m,
                            UserId = "056a8e45-40e3-4665-ae80-a499e7ed4fd6"
                        },
                        new
                        {
                            Id = 33,
                            CompanyEmail = "johndoe33@company.gmail",
                            Country = "UK",
                            DepartmentId = 4,
                            EncryptedIBAN = "R0I2NU5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2167m,
                            UserId = "af77617b-e2b5-4e09-8d9e-85d222d82564"
                        },
                        new
                        {
                            Id = 34,
                            CompanyEmail = "johndoe34@company.gmail",
                            Country = "UK",
                            DepartmentId = 5,
                            EncryptedIBAN = "R0IyN05XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 4965m,
                            UserId = "702b60fd-a373-4099-8c5a-5f4bbd869668"
                        },
                        new
                        {
                            Id = 35,
                            CompanyEmail = "johndoe35@company.gmail",
                            Country = "UK",
                            DepartmentId = 6,
                            EncryptedIBAN = "R0I5OE5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2847m,
                            UserId = "c16dbd99-0405-4ada-9298-1240a2f3c1b1"
                        },
                        new
                        {
                            Id = 36,
                            CompanyEmail = "johndoe36@company.gmail",
                            Country = "Germany",
                            DepartmentId = 1,
                            EncryptedIBAN = "REU1ODM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1536m,
                            UserId = "e96bcfb5-e8fe-43e3-8cce-7d34630d395d"
                        },
                        new
                        {
                            Id = 37,
                            CompanyEmail = "johndoe37@company.gmail",
                            Country = "France",
                            DepartmentId = 2,
                            EncryptedIBAN = "RlI3MDMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2157m,
                            UserId = "91325d43-de93-49d9-8e08-f48e142a446a"
                        },
                        new
                        {
                            Id = 38,
                            CompanyEmail = "johndoe38@company.gmail",
                            Country = "Germany",
                            DepartmentId = 3,
                            EncryptedIBAN = "REU1NTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4151m,
                            UserId = "4bcc0e46-09c7-451d-b3d6-2f7d93ac12ae"
                        },
                        new
                        {
                            Id = 39,
                            CompanyEmail = "johndoe39@company.gmail",
                            Country = "France",
                            DepartmentId = 4,
                            EncryptedIBAN = "RlIxMzMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2073m,
                            UserId = "d31ab548-c3ee-489e-b6f4-6794a39beefc"
                        },
                        new
                        {
                            Id = 40,
                            CompanyEmail = "johndoe40@company.gmail",
                            Country = "UK",
                            DepartmentId = 5,
                            EncryptedIBAN = "R0I4Nk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 3177m,
                            UserId = "6d83b64c-4eea-4f37-83a9-7353d0e957d6"
                        },
                        new
                        {
                            Id = 41,
                            CompanyEmail = "johndoe41@company.gmail",
                            Country = "France",
                            DepartmentId = 6,
                            EncryptedIBAN = "RlIyOTMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2688m,
                            UserId = "18eaacb8-e4be-4869-9551-7208c70b7824"
                        },
                        new
                        {
                            Id = 42,
                            CompanyEmail = "johndoe42@company.gmail",
                            Country = "Germany",
                            DepartmentId = 1,
                            EncryptedIBAN = "REU4NjM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1723m,
                            UserId = "9d094fdf-c338-4301-ace7-91d4ca9f7ad0"
                        },
                        new
                        {
                            Id = 43,
                            CompanyEmail = "johndoe43@company.gmail",
                            Country = "France",
                            DepartmentId = 2,
                            EncryptedIBAN = "RlI4MDMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2192m,
                            UserId = "c5c8a4a8-5e08-4cb9-a1a8-edc657f42719"
                        },
                        new
                        {
                            Id = 44,
                            CompanyEmail = "johndoe44@company.gmail",
                            Country = "UK",
                            DepartmentId = 3,
                            EncryptedIBAN = "R0I1OE5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4668m,
                            UserId = "729717c6-1ddc-4c09-8117-a254c2d5c263"
                        },
                        new
                        {
                            Id = 45,
                            CompanyEmail = "johndoe45@company.gmail",
                            Country = "UK",
                            DepartmentId = 4,
                            EncryptedIBAN = "R0I4Mk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2076m,
                            UserId = "a416fab3-37c5-4771-8e73-e37363d4dc2f"
                        },
                        new
                        {
                            Id = 46,
                            CompanyEmail = "johndoe46@company.gmail",
                            Country = "UK",
                            DepartmentId = 5,
                            EncryptedIBAN = "R0IyM05XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 2071m,
                            UserId = "10d13800-c4cb-4125-a9de-2baf160b09fc"
                        },
                        new
                        {
                            Id = 47,
                            CompanyEmail = "johndoe47@company.gmail",
                            Country = "UK",
                            DepartmentId = 6,
                            EncryptedIBAN = "R0IyNk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2512m,
                            UserId = "df694b56-2105-48bb-a29d-977166995cd4"
                        },
                        new
                        {
                            Id = 48,
                            CompanyEmail = "johndoe48@company.gmail",
                            Country = "Germany",
                            DepartmentId = 1,
                            EncryptedIBAN = "REUyODM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1546m,
                            UserId = "10f6c8e2-b8ee-489b-a654-b3c96faec0e7"
                        },
                        new
                        {
                            Id = 49,
                            CompanyEmail = "johndoe49@company.gmail",
                            Country = "UK",
                            DepartmentId = 2,
                            EncryptedIBAN = "R0IzN05XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2075m,
                            UserId = "b6ed985c-13ed-4916-8d38-b5a45cb6665c"
                        },
                        new
                        {
                            Id = 50,
                            CompanyEmail = "johndoe50@company.gmail",
                            Country = "UK",
                            DepartmentId = 3,
                            EncryptedIBAN = "R0I0N05XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4675m,
                            UserId = "7b6b47ee-1bf8-4aae-90fc-4c1e268a1371"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.SalaryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryRecords");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "3349f823-1c6f-4abc-a21c-9cdc31f02117",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "12015f7c-1ec1-41c0-9157-39ebd5971baa",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "cf5569fe-7c04-47fe-8208-5416841f523b",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2a561aab-d12b-4391-9132-f7da67125396",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "d2e4957d-cef0-4062-a6c9-3f588f13f58f",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "6951b2ae-f6f4-4da5-9136-b25004c28f9c",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "0b2c6feb-b642-49f8-84ef-680d3ff2c344",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "726d58c1-73fa-43fb-b3fb-48ec29b2ac5c",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "f7afdc1e-c904-44e2-9224-43e4aecbc673",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "e2a94c68-334a-4305-b96b-46693e124d1b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8e0bcaef-52af-4021-b2f3-1f2770d38d52",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "c5c20525-4a8f-4a6f-bd5f-70cafc974b97",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7da74fd5-160f-4cd6-91b2-8628f4f47a83",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4eaa9c9e-8590-4534-960b-4c72ec5de01b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7dd20390-ce34-4e8a-9989-7861830cb12d",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "5b2bc7e2-8f2c-43c5-9027-99b354272660",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6096bf5f-c034-4c83-91d5-f911cbe361ea",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "52404cf1-e1de-4159-a6c7-206d7eb1782a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "06ab1e2f-9194-447b-9847-70297d410585",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d16589d3-e5e3-4c10-a858-c37d115d10ba",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5328b4b2-c307-4932-8547-57857a70b30c",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "4b00f983-a2b3-4366-955b-85d1fa2ae6fb",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "bbfed021-45ee-40a5-97b8-a2ac21c6d198",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ab4fa6d6-d7b7-42da-a023-7b1a8e3d0b91",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "1023b4e0-446e-460b-8f95-aa88c57c26df",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e871640c-a4bd-4299-b669-def9e01d4e67",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "bd265674-3975-4d45-b2f4-dab47fe760f9",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "a95df43d-3e6d-4291-989a-3aa48063e1ac",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f08881d5-7483-4eea-afc7-a1c402226c06",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "c04d52fb-9fe6-4782-80cc-1867821fce44",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8d51c159-6db7-466f-a48d-9dfecc31c543",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "994946ef-8443-4db5-9369-fe1c871577d1",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "fc28eb59-dcf7-46bf-81ff-bd16ef7171d8",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "661d2c59-4abf-4f5f-b743-98be0e5644a9",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "056a8e45-40e3-4665-ae80-a499e7ed4fd6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "af77617b-e2b5-4e09-8d9e-85d222d82564",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "702b60fd-a373-4099-8c5a-5f4bbd869668",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "c16dbd99-0405-4ada-9298-1240a2f3c1b1",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e96bcfb5-e8fe-43e3-8cce-7d34630d395d",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "91325d43-de93-49d9-8e08-f48e142a446a",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4bcc0e46-09c7-451d-b3d6-2f7d93ac12ae",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d31ab548-c3ee-489e-b6f4-6794a39beefc",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6d83b64c-4eea-4f37-83a9-7353d0e957d6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "18eaacb8-e4be-4869-9551-7208c70b7824",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9d094fdf-c338-4301-ace7-91d4ca9f7ad0",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "c5c8a4a8-5e08-4cb9-a1a8-edc657f42719",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "729717c6-1ddc-4c09-8117-a254c2d5c263",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a416fab3-37c5-4771-8e73-e37363d4dc2f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "10d13800-c4cb-4125-a9de-2baf160b09fc",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "df694b56-2105-48bb-a29d-977166995cd4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "10f6c8e2-b8ee-489b-a654-b3c96faec0e7",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "b6ed985c-13ed-4916-8d38-b5a45cb6665c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7b6b47ee-1bf8-4aae-90fc-4c1e268a1371",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HumanCapitalManagement.Data.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.SalaryRecord", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Employee", "Employee")
                        .WithMany("SalaryRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Navigation("SalaryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
