// <auto-generated />
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanManagementCapital.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "johndoe1@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3009.0m,
                            UserId = "7b245aad-b578-4301-8087-1ea820e39562"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "johndoe2@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 6448.5m,
                            UserId = "ca3606ca-ab04-47dc-9004-18fb129fe813"
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "johndoe3@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3019.5m,
                            UserId = "e76f1d06-a5be-4000-aa0e-53e0cbee6b13"
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "johndoe4@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 5560.5m,
                            UserId = "418ebbc6-a571-4b16-bddb-3e10c85a94a0"
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "johndoe5@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 4482.0m,
                            UserId = "da3962a7-8c95-47e3-9fba-460090c2205c"
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "johndoe6@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2385.0m,
                            UserId = "3753947d-e359-443d-b5b9-e01636c8b306"
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "johndoe7@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2132m,
                            UserId = "76fff0d3-0dfb-44ed-92ff-5fa88274efb7"
                        },
                        new
                        {
                            Id = 8,
                            CompanyEmail = "johndoe8@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4372m,
                            UserId = "71370e19-12e7-427d-a2cc-02bec1b032a0"
                        },
                        new
                        {
                            Id = 9,
                            CompanyEmail = "johndoe9@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Content Writer",
                            LastName = "Doe",
                            Salary = 2030m,
                            UserId = "82678257-b20a-4ee8-8a8f-af9ab8d197d4"
                        },
                        new
                        {
                            Id = 10,
                            CompanyEmail = "johndoe10@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 3266m,
                            UserId = "40e5148f-fa0b-4d0b-a998-d8ae7b46c2e8"
                        },
                        new
                        {
                            Id = 11,
                            CompanyEmail = "johndoe11@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2952m,
                            UserId = "bfc1e140-3bf5-4b88-83e4-c9c8818edd29"
                        },
                        new
                        {
                            Id = 12,
                            CompanyEmail = "johndoe12@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1634m,
                            UserId = "e32878cb-895b-4f7e-be8b-24bffbb0908b"
                        },
                        new
                        {
                            Id = 13,
                            CompanyEmail = "johndoe13@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2130m,
                            UserId = "924692db-40ba-4c40-bb30-9e2df2a31ba7"
                        },
                        new
                        {
                            Id = 14,
                            CompanyEmail = "johndoe14@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4011m,
                            UserId = "8c4e6128-4c38-4a55-a37b-7d6df6ce0450"
                        },
                        new
                        {
                            Id = 15,
                            CompanyEmail = "johndoe15@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2059m,
                            UserId = "e56960b3-1ea4-49b2-91e4-e97b3d674370"
                        },
                        new
                        {
                            Id = 16,
                            CompanyEmail = "johndoe16@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 3230m,
                            UserId = "47e0fcda-58c0-4590-964c-dae179f92932"
                        },
                        new
                        {
                            Id = 17,
                            CompanyEmail = "johndoe17@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2557m,
                            UserId = "f5e404c4-33c8-44e7-9334-49eb7fc18b2d"
                        },
                        new
                        {
                            Id = 18,
                            CompanyEmail = "johndoe18@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1514m,
                            UserId = "d28b7523-bf79-43a3-b00b-cfbcad195925"
                        },
                        new
                        {
                            Id = 19,
                            CompanyEmail = "johndoe19@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Financial Analyst",
                            LastName = "Doe",
                            Salary = 2169m,
                            UserId = "0dbd5552-6f1f-4d82-881c-f22d85c2789b"
                        },
                        new
                        {
                            Id = 20,
                            CompanyEmail = "johndoe20@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4993m,
                            UserId = "d791bf20-7fce-4950-9355-f79812bd56fd"
                        },
                        new
                        {
                            Id = 21,
                            CompanyEmail = "johndoe21@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2117m,
                            UserId = "82b00941-53b0-43e8-be9b-d499f99422df"
                        },
                        new
                        {
                            Id = 22,
                            CompanyEmail = "johndoe22@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 3588m,
                            UserId = "06b8a530-99ed-43e0-868d-e61bddb70fad"
                        },
                        new
                        {
                            Id = 23,
                            CompanyEmail = "johndoe23@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2875m,
                            UserId = "914d74f3-e00f-4832-bbfc-a1a8fa197dd5"
                        },
                        new
                        {
                            Id = 24,
                            CompanyEmail = "johndoe24@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1551m,
                            UserId = "8b3b6a36-740b-4ff4-90a2-68f4d648268f"
                        },
                        new
                        {
                            Id = 25,
                            CompanyEmail = "johndoe25@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2199m,
                            UserId = "5e469dbc-cb73-468d-96f6-08775e3b914f"
                        },
                        new
                        {
                            Id = 26,
                            CompanyEmail = "johndoe26@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4484m,
                            UserId = "ddad886a-0374-4216-8a0e-44b97d9415b6"
                        },
                        new
                        {
                            Id = 27,
                            CompanyEmail = "johndoe27@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2017m,
                            UserId = "ce329555-f617-4932-8612-35aa95ae7b73"
                        },
                        new
                        {
                            Id = 28,
                            CompanyEmail = "johndoe28@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Account Executive",
                            LastName = "Doe",
                            Salary = 3488m,
                            UserId = "789e8ba5-d2a7-474c-9388-709f8d555444"
                        },
                        new
                        {
                            Id = 29,
                            CompanyEmail = "johndoe29@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2891m,
                            UserId = "01e39ff9-7d2c-4adc-af9a-1def1731f356"
                        },
                        new
                        {
                            Id = 30,
                            CompanyEmail = "johndoe30@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1751m,
                            UserId = "71873536-d293-4abe-b1a8-c3e3409e4419"
                        },
                        new
                        {
                            Id = 31,
                            CompanyEmail = "johndoe31@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2143m,
                            UserId = "6f45e132-0852-4469-abfb-44a8310901ec"
                        },
                        new
                        {
                            Id = 32,
                            CompanyEmail = "johndoe32@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4380m,
                            UserId = "36848f24-c34a-4b47-a978-019a7edf5916"
                        },
                        new
                        {
                            Id = 33,
                            CompanyEmail = "johndoe33@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2185m,
                            UserId = "d3bed2dd-fc8a-4d79-8c55-fa719ae3d50c"
                        },
                        new
                        {
                            Id = 34,
                            CompanyEmail = "johndoe34@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 3647m,
                            UserId = "1f8ce4af-5006-4286-a3a6-2afe3afcdfaf"
                        },
                        new
                        {
                            Id = 35,
                            CompanyEmail = "johndoe35@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Operations Specialist",
                            LastName = "Doe",
                            Salary = 2939m,
                            UserId = "27b82b23-1b44-4109-b67e-436096e44aed"
                        },
                        new
                        {
                            Id = 36,
                            CompanyEmail = "johndoe36@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "HR Generalist",
                            LastName = "Doe",
                            Salary = 1641m,
                            UserId = "0c514623-a8dd-4596-a8bb-44aa2cedff5d"
                        },
                        new
                        {
                            Id = 37,
                            CompanyEmail = "johndoe37@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2167m,
                            UserId = "e433d64a-67b7-41bf-a601-b0699aa8b919"
                        },
                        new
                        {
                            Id = 38,
                            CompanyEmail = "johndoe38@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4582m,
                            UserId = "d3c43796-5ef4-4ffe-937e-5ba4c5a8482b"
                        },
                        new
                        {
                            Id = 39,
                            CompanyEmail = "johndoe39@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "Social Media Manager",
                            LastName = "Doe",
                            Salary = 2127m,
                            UserId = "b380b92c-3735-479f-9ac9-ff009e753037"
                        },
                        new
                        {
                            Id = 40,
                            CompanyEmail = "johndoe40@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 2578m,
                            UserId = "5441893b-7bca-418d-870d-fbe7eb16bfe2"
                        },
                        new
                        {
                            Id = 41,
                            CompanyEmail = "johndoe41@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2648m,
                            UserId = "5f86318f-6981-4378-b202-b0323193f477"
                        },
                        new
                        {
                            Id = 42,
                            CompanyEmail = "johndoe42@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1574m,
                            UserId = "d1062501-1fa7-432a-8580-4c338adcdab2"
                        },
                        new
                        {
                            Id = 43,
                            CompanyEmail = "johndoe43@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2173m,
                            UserId = "a38c9770-bc32-4740-bcea-ee0f6881e0d8"
                        },
                        new
                        {
                            Id = 44,
                            CompanyEmail = "johndoe44@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4650m,
                            UserId = "a7ac7ab2-ed5b-4bc4-9e3e-a1df13c1992f"
                        },
                        new
                        {
                            Id = 45,
                            CompanyEmail = "johndoe45@company.gmail",
                            DepartmentId = 4,
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2009m,
                            UserId = "67915455-ec4a-4f16-9de9-85f70f49a244"
                        },
                        new
                        {
                            Id = 46,
                            CompanyEmail = "johndoe46@company.gmail",
                            DepartmentId = 5,
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 4352m,
                            UserId = "5d6426fb-2a54-4baa-9ed2-507ae47c71f6"
                        },
                        new
                        {
                            Id = 47,
                            CompanyEmail = "johndoe47@company.gmail",
                            DepartmentId = 6,
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2888m,
                            UserId = "f69a9979-f663-4757-9892-7bea2980908c"
                        },
                        new
                        {
                            Id = 48,
                            CompanyEmail = "johndoe48@company.gmail",
                            DepartmentId = 1,
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1672m,
                            UserId = "a640a904-76b0-4b68-9c94-1e9881c14efb"
                        },
                        new
                        {
                            Id = 49,
                            CompanyEmail = "johndoe49@company.gmail",
                            DepartmentId = 2,
                            FirstName = "John",
                            JobTitle = "Tax Specialist",
                            LastName = "Doe",
                            Salary = 2177m,
                            UserId = "50ad756f-75a4-42ac-a9c2-287301f4b518"
                        },
                        new
                        {
                            Id = 50,
                            CompanyEmail = "johndoe50@company.gmail",
                            DepartmentId = 3,
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4359m,
                            UserId = "10744729-d70f-45dc-bfa9-6427490d32ce"
                        });
                });

            modelBuilder.Entity("HumanManagementCapital.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7b245aad-b578-4301-8087-1ea820e39562",
                            ConcurrencyStamp = "d348c3f8-9fa3-43dd-80d2-6f66298993f2",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEDV8AyvelMSZzrxkGrn8FE+wOo0e/ZqgWPJtAgsxtyYeZpfk3ChoRjDlnPif1xz5Bg==",
                            SecurityStamp = "a56c8134-b438-46f4-9184-7267b72f99c0",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "ca3606ca-ab04-47dc-9004-18fb129fe813",
                            ConcurrencyStamp = "ba56a99d-3e81-4e66-af23-b5efdb2df671",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEDkwku6UFjq1fYpZ+PkJsE52/x0y2irCwYXP2irF0yNWpsLPaBnATJS+AoAkcBL9Rw==",
                            SecurityStamp = "271793c6-cfc7-46e3-b41d-8a443c59bbf3",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "e76f1d06-a5be-4000-aa0e-53e0cbee6b13",
                            ConcurrencyStamp = "c573b1a3-39f2-41b9-8090-a8d5c5b3aa3a",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEEYs2ISDY1gRsOamzYXOqJ44n9icTO8JETJbwrUSpit7DGxEG1S4MdfdX0YMlDtYRQ==",
                            SecurityStamp = "f8311b48-b779-44a4-a71f-15fe9958a91f",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "418ebbc6-a571-4b16-bddb-3e10c85a94a0",
                            ConcurrencyStamp = "f1487db4-f3a9-404e-8ee3-ca9a4a1f2b75",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEKNddsO/yA2c9nzRmR5x/oiOPFV06kVzkvEBRasS+YXFHW2PSsxEd8blsZeFojy5IA==",
                            SecurityStamp = "5d6dbd7e-27ad-45be-91e8-bacf8bc7fe99",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "da3962a7-8c95-47e3-9fba-460090c2205c",
                            ConcurrencyStamp = "f4cb687a-c2b0-42c3-9173-c4579d1a77fc",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAEKKd9mIXTA7c4H2Ywfqs9lQk80CbsSDN1jzXX0i0nEgd0mBXh9VFxo/uqezQ0iQIQQ==",
                            SecurityStamp = "77cf745f-dd45-4885-939c-52fc56646551",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "3753947d-e359-443d-b5b9-e01636c8b306",
                            ConcurrencyStamp = "c1b92ab3-f8d8-473d-b177-3a46098a6154",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAENuz7in1l0gD/9kgUNsCicMWd2hacD+/973lBRPjHmdjnK0J11MDrZQCg2iCn69XqQ==",
                            SecurityStamp = "6289e6e9-e7d5-4cfa-9fa3-86fc951f90a0",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "76fff0d3-0dfb-44ed-92ff-5fa88274efb7",
                            ConcurrencyStamp = "dfed1792-081c-4040-b935-4dea83836a5a",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAEDLB5XmYHlvu40Ok7p1h9Iak+1lD0YD/0Y/B4uG6mIK8VKXtHWmoYmSaMPN+fZa0DA==",
                            SecurityStamp = "5806de1e-1e8f-45f8-9427-0df485066928",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "71370e19-12e7-427d-a2cc-02bec1b032a0",
                            ConcurrencyStamp = "2fc38194-4599-4ed6-8203-87823c1bb06f",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAEJEnQIBi37xVYjzpF1Ms6ssMBTaCA7+JET9wyFkUNY5ZopGAbGSEWWZ+Lul2t/8Z5g==",
                            SecurityStamp = "b2e6d832-e325-44a0-94ee-b497b8d009f1",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "82678257-b20a-4ee8-8a8f-af9ab8d197d4",
                            ConcurrencyStamp = "cec74a10-f1fa-42c1-90a9-0d84e3f915d7",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEP0vq0jFh4BwXTweqAPV5aOpsCji0hplOdDNHcpyRTc+YsC17C7dM2q+UzR8TrGHKQ==",
                            SecurityStamp = "eadf2e19-960f-4238-b88e-d81c305d2c5b",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "40e5148f-fa0b-4d0b-a998-d8ae7b46c2e8",
                            ConcurrencyStamp = "64ca0af7-cf20-4814-ba43-eb49457c3fdc",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEFbk1sUeR/KtmHsuEVB2cp1660Jes1Y3Yx42mNsxhaJgmz3QLUKm6vb99LKRirrAfw==",
                            SecurityStamp = "bc2fec2c-cfa7-41c4-9b04-e133ee387cd6",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "bfc1e140-3bf5-4b88-83e4-c9c8818edd29",
                            ConcurrencyStamp = "cff48c20-ce77-4db9-bf3d-756ae9a422f9",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAEOvgn/USPJbSzdk0lo6zE1iqRRfbECUsmadajp4Tpo7Db4olr5CLADoXscBlWFPTJg==",
                            SecurityStamp = "80a374f2-2702-4f96-9de9-1c7530fbb47d",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "e32878cb-895b-4f7e-be8b-24bffbb0908b",
                            ConcurrencyStamp = "68498fec-a41d-4f93-bfe4-b140e1a104ce",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAEJJwZTxkvNGkC5teFEXVSWj0J4aUBsE5W2FpZL97BecG2fNoGlWaBJS/x9Gt56m4Kg==",
                            SecurityStamp = "37ce918f-98f5-41d0-838e-f13ebc0ea833",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "924692db-40ba-4c40-bb30-9e2df2a31ba7",
                            ConcurrencyStamp = "90aabbd7-65b6-4a73-8a89-4cccf30b07ca",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEBRCFSfdw1F8NZ8Uuvbk430bEz7VR1JbrU+jnrHxlGy70RsjGbPXvjzrE7wYgklt6Q==",
                            SecurityStamp = "4842466c-399c-4c28-9d3e-a659dd86c135",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "8c4e6128-4c38-4a55-a37b-7d6df6ce0450",
                            ConcurrencyStamp = "da67d075-1eb0-465c-93b0-4fb1c0f65d69",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAECML+KgMPugQRVGd8isGOBPPcggMGcKFGTf64hW7v/GGaB1kMl8ZKayfQdTRaGa6Ig==",
                            SecurityStamp = "ca89504f-b703-4013-aba3-da29071a3ceb",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "e56960b3-1ea4-49b2-91e4-e97b3d674370",
                            ConcurrencyStamp = "ff97c646-e938-48e4-a620-d9135a670683",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAEGyNyF24IueFUwPG+R2sbar/K0P48aT9TueERBIKMwwxRZlCdUVP2i/E1bcqB123nw==",
                            SecurityStamp = "30323bbe-515b-44e9-8b05-93f0b18977b2",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "47e0fcda-58c0-4590-964c-dae179f92932",
                            ConcurrencyStamp = "2934492c-fe63-4d44-9682-50d4c41a60ae",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAEEWcESmpFREM+UUvY2dForFjK4Veezgv8mDGikJ2rNJVwHuLpd042giFRS9jvMhmvw==",
                            SecurityStamp = "b01ccc60-41c6-4ccb-b98a-938f3f455349",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "f5e404c4-33c8-44e7-9334-49eb7fc18b2d",
                            ConcurrencyStamp = "51990a5a-4548-4234-851b-d378ff9de57e",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAECtX5rVl4qq4876RPfNWhOC7PD9VsIp3AjzACbfZ63COKUP7BP0EwJQKPX5aKHDB6A==",
                            SecurityStamp = "56bf3774-7cc8-491d-99b0-81d81844decc",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "d28b7523-bf79-43a3-b00b-cfbcad195925",
                            ConcurrencyStamp = "a50c93db-9021-49e3-970d-acf682f319c1",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAEEQy3LGvrwnn4ueJRcvzjgsUZItrEmYSLhPOYevEKXh3MhESxz8n1f3/Q+uBW/fHUQ==",
                            SecurityStamp = "2287af12-f51e-4446-8087-264f5708d593",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "0dbd5552-6f1f-4d82-881c-f22d85c2789b",
                            ConcurrencyStamp = "0e2a5797-b293-40b2-93ca-5fd68fc9bd78",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAELXWSwT+Brvcno0ZILx5rorDi88+kpq24f6gZlzwNOPHsIHQuAq6OYbSFrkuS0Hq8A==",
                            SecurityStamp = "49b8e7f4-14ce-4d0a-8560-bd4fd0d220fd",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "d791bf20-7fce-4950-9355-f79812bd56fd",
                            ConcurrencyStamp = "efda7e28-b1cd-49fa-88da-aac78b85e077",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAEHBYbUDvI9YPWfx43Ko1k5ccDikCRYKrwyNEaFbHXtNaH7TCvFGNVDFzDsHumPMPgg==",
                            SecurityStamp = "25e57caa-9419-4cc3-8478-1f38354a2371",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "82b00941-53b0-43e8-be9b-d499f99422df",
                            ConcurrencyStamp = "8a19af87-4954-4467-bd13-45d66a79cf87",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAECjJs8iiZKFWQH7bgXg8XoF5DAImzDcl2/aeVL6WhdfZXkibLcZDdyA/EPfSpjraIg==",
                            SecurityStamp = "faf59d58-605c-4aae-bc50-40197e49774a",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "06b8a530-99ed-43e0-868d-e61bddb70fad",
                            ConcurrencyStamp = "4942aadd-42a6-4a6a-a6d2-2370e1c49c7e",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAEKXcLPWDjvoNi1xu0GJ6t1OCiBSRZUAdJ83AtcYmu+SlKT5DYK1NeKcva34uoOpRBA==",
                            SecurityStamp = "f9ab82b8-a19e-4fed-93e9-965ad4bb238e",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "914d74f3-e00f-4832-bbfc-a1a8fa197dd5",
                            ConcurrencyStamp = "074d885f-3cce-44f1-89bc-c28677d78a76",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEIAaIEmyduR0Taq6mXBwPazDGp7b6r6e29KxpzZXQ/pUwtwM/CSFvW5w3OyAGsS4Ng==",
                            SecurityStamp = "d77ab191-0da9-4d53-979c-557142b1ecef",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "8b3b6a36-740b-4ff4-90a2-68f4d648268f",
                            ConcurrencyStamp = "51fb44b2-5831-41e3-8b93-5ea43b460b95",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAENGEphxrA9r6Tg9EI2IKzg1l5+mFHGXK31mn+719wMalHn54Kdod5kDVGodLyYlaiQ==",
                            SecurityStamp = "1be4a6c6-0f5c-4ebf-b887-e72ef7018474",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "5e469dbc-cb73-468d-96f6-08775e3b914f",
                            ConcurrencyStamp = "3c42e70a-6a20-49a1-a3ba-e27d86dd0ff2",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEBgadceVSe7OjP0e+dmOXVdVikDtLdclDtbirIOu/YTdISP0Rfog1UUvIed6o0Rx6g==",
                            SecurityStamp = "9c5b6638-a9d0-4e2e-a608-36397c62b6d0",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "ddad886a-0374-4216-8a0e-44b97d9415b6",
                            ConcurrencyStamp = "91b0a5f6-41a7-4bfd-8905-7227616fc954",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAEFJ6Rr9zkcWsrBY1rWVw+21ixNqIsDejcKjLq7VkIf9GExIpjPjgSSbpZWb8DJcExg==",
                            SecurityStamp = "e787522a-ccd1-4ace-a2d3-d41b29f9f627",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "ce329555-f617-4932-8612-35aa95ae7b73",
                            ConcurrencyStamp = "e924631a-58e7-4e59-81a8-377b078d58c8",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAEPCGQ49cGJCQ2WgP+FOtps1JuDlw6YVGSXr6/SZQ2F5+gEkbaZAAjGjpydjuKovVBg==",
                            SecurityStamp = "a476b6fb-4428-45d9-bea6-44042ddaa335",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "789e8ba5-d2a7-474c-9388-709f8d555444",
                            ConcurrencyStamp = "a202ce54-2913-4733-a79a-4c67b484fdfd",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEPPIVZoQNjpnACcerk5gmAik3gtX4e2FkMQUixy0GaQtI4gfNxdCqs77NZ2beVBxBQ==",
                            SecurityStamp = "6a8a5d09-9c80-4401-9c6f-5ba702caf3e0",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "01e39ff9-7d2c-4adc-af9a-1def1731f356",
                            ConcurrencyStamp = "851a4131-d314-42c2-b61a-650c22eceee7",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAELvCwBQLodhq978IJkmTvDbvhubvnPMprSCnHQJ5RL+5MLeO8LFLea0Fp7wgb/VOnw==",
                            SecurityStamp = "dda604e9-e615-4715-998f-46983efb21c9",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "71873536-d293-4abe-b1a8-c3e3409e4419",
                            ConcurrencyStamp = "285dba5d-8e14-4bf8-9147-98c3edc42643",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAEGjcVIXoE+Q7WbIhDQ9L5vUiIe06xNryoRNwwoo2zarFNT39uqfXbS9XI8k4tgReAQ==",
                            SecurityStamp = "3d696bc5-c452-4be9-9e97-c199677f72c1",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "6f45e132-0852-4469-abfb-44a8310901ec",
                            ConcurrencyStamp = "c1d6c0b2-0421-4131-a575-f203db98a720",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEEaHe5JMwbODGN83tc6UMSTPcnZYhCwg7i5uQSdYhuBSuIJQGYhMbaTA9ge9hOGriw==",
                            SecurityStamp = "1dee41b7-375d-4066-88a1-1ebec57da45b",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "36848f24-c34a-4b47-a978-019a7edf5916",
                            ConcurrencyStamp = "df1a5af7-2ca4-4b8c-9eaa-af8be2b27d53",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEIb2ejkK3r8zC8GZXrMEldvEOX8Die25wPJbknlRliI48kQoQgMzwpCdqB9VhvAZOQ==",
                            SecurityStamp = "bcf1acd7-f0fc-46c0-8b23-7b3db89e4fce",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "d3bed2dd-fc8a-4d79-8c55-fa719ae3d50c",
                            ConcurrencyStamp = "22395dc9-ce67-4ea8-9e9b-099fcc9c3137",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAEN1Stkit1UlCGhTkErihswg5+lifqddEmrepCUJxGDyj6sOUgxWbJF5Ecwh5rNF+4w==",
                            SecurityStamp = "094c7c71-cb9f-4262-8927-0c8f9e6611c4",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "1f8ce4af-5006-4286-a3a6-2afe3afcdfaf",
                            ConcurrencyStamp = "14cf51a4-2e50-4a20-bfbb-559ca9a4e596",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAEMiX8laybEU2rNFSqXlEx64ffrUsWQ8bF/bZIusf51grL490lgS1CIf81fXd97eFYQ==",
                            SecurityStamp = "d17737c9-88bf-46bf-b8b0-595251449141",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "27b82b23-1b44-4109-b67e-436096e44aed",
                            ConcurrencyStamp = "0f69221b-b1f5-4a70-a345-786c4cd2e776",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAEPkKEWEUP+kK9QCC2G6HtBbC8w+SYwNWe069c7jiLjdXc9rP9YG02jzNOerVDWshDA==",
                            SecurityStamp = "ca043a9f-b4ff-42f5-a3ad-a6c538fe6f5d",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "0c514623-a8dd-4596-a8bb-44aa2cedff5d",
                            ConcurrencyStamp = "ac7196b1-dee3-4fa0-9469-88ed1f442f9f",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAEL1wJB3Ey6ZOsU0uQbeoBWEh4RQOoijuzaE87aTGzHlYn6upouLPHvMA8Oc50nSDVA==",
                            SecurityStamp = "0e38cd33-b23f-416f-96b1-b4fa564e3538",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "e433d64a-67b7-41bf-a601-b0699aa8b919",
                            ConcurrencyStamp = "896a4d2e-4dc7-4b48-8d17-10c1ff7af30d",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEDz+ElnGRp7L0MJ/izzFtKZr9WP26qMWNFy5aJJY2r8GGcJGRSCbhpKL/DrPPzLaGw==",
                            SecurityStamp = "ac8f1b73-6d7b-4e71-bbdf-172b8e07a3a2",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "d3c43796-5ef4-4ffe-937e-5ba4c5a8482b",
                            ConcurrencyStamp = "90232534-f5e6-4e69-ae6a-c2c0f9bbdaac",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAEGofrNnc/M84cmCmdn0O1cKPMdY5iiccMSqCytLgIJquEQhuaHc5AF26noKdvlqgGw==",
                            SecurityStamp = "bf03b34f-060d-44de-a7a9-e5196f5fe589",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "b380b92c-3735-479f-9ac9-ff009e753037",
                            ConcurrencyStamp = "f70ba16b-cd4f-4a51-a634-382e8f4d8054",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEGO9sIsqKQmyJ6N04hL+VuraAOEXue0+WF5McVSrJZ0oAyTkr694RNNMFZxkdhjmrg==",
                            SecurityStamp = "b3a541d7-9cfc-44f0-9b04-6ff0410f01f8",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "5441893b-7bca-418d-870d-fbe7eb16bfe2",
                            ConcurrencyStamp = "20ae9c06-aab6-4a90-b0af-ab369fd4428b",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEMscc3nCiw3BmiDZidJZofmnvG4qXKOhxjR6xPkR6WNuNpKMeuTditHBwhw1OLfGvw==",
                            SecurityStamp = "93d32b47-040d-4ec6-a9c8-25f2fa32e348",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "5f86318f-6981-4378-b202-b0323193f477",
                            ConcurrencyStamp = "cf4f2793-8b5b-4d01-86c2-0b072fb5bb82",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAEGZI6PCKA1/Mw8RChnuncHz1BMftl56bQ8CnU9+2ReX5TU8/WE5FDEAvD82jTEofbg==",
                            SecurityStamp = "b9f142ee-1589-48a0-af0e-118bb75d5fa6",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "d1062501-1fa7-432a-8580-4c338adcdab2",
                            ConcurrencyStamp = "28b264fc-0245-4902-a9a7-94e680908f9f",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAECPtbqjb8HEVOy58qWd9K+Ogk0a8KkZj7GCvAb4p08vhLKZ/QdyHCk1Gt3G/RDQ1KA==",
                            SecurityStamp = "8b914adb-fded-4ba7-9dcf-02cefbac7f19",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "a38c9770-bc32-4740-bcea-ee0f6881e0d8",
                            ConcurrencyStamp = "95b9faac-c894-4cb0-8e8f-ebdcc01a59c4",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAEGwy3/xTRNAEhlyt3wmsPlZjEf8BqaDcEdA2p1DdJlDNqP2rzyg3fDoCM3FG/EUx8w==",
                            SecurityStamp = "434fca36-4905-47ef-837a-b00414dbfee9",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "a7ac7ab2-ed5b-4bc4-9e3e-a1df13c1992f",
                            ConcurrencyStamp = "99633d99-a3b2-47e1-b986-cd2bff3f6f3a",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAEAeoVgfZb7Ak9izQ4KDkMOIgOTzIIxk+ZW6kxPpL05oO9eWCw52+EwPrCh/l5kobyA==",
                            SecurityStamp = "29d6b513-eb8e-4728-bfdb-be4279699a91",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "67915455-ec4a-4f16-9de9-85f70f49a244",
                            ConcurrencyStamp = "2f12c9b8-a2d1-4234-b399-da43558a30d3",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAEMeMgIaKLlyVao7Ul6wr7W4jUa1Bzd+2oN+h9P9+iDmwTRJCdN/LRJAfi+HYRnFwuA==",
                            SecurityStamp = "196c81f9-24b4-4fb2-bf42-6b51af152cfe",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "5d6426fb-2a54-4baa-9ed2-507ae47c71f6",
                            ConcurrencyStamp = "a290e093-6082-41f4-97b9-4694f2c66743",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAEFEGHHirIbLHxI5wi+fTsgXY6XhP0v3dqDJViOamKsl+ENsiwIfCDdv2Ra110jpoRg==",
                            SecurityStamp = "0260bf12-4435-4bd0-a46c-0073e03bc88b",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "f69a9979-f663-4757-9892-7bea2980908c",
                            ConcurrencyStamp = "54057a41-099b-4304-8993-5ed1f681d2f7",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAEGFN0ChK7Vnc1+CJDxYmAnjB6toNPOBKnH4caWzGAvXlp7IwvrV3qRVG6h42l5zDwg==",
                            SecurityStamp = "a7d5bbe3-33ec-4472-8595-7206375e9465",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "a640a904-76b0-4b68-9c94-1e9881c14efb",
                            ConcurrencyStamp = "3233b51f-3c9a-43e2-a6b5-6bdd642bd5fd",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAEHv9g55SUF/Utt8EqQABGEzkO0/EBUK+lBp3qi8/yrKFc7GToimY+3IJBw7uBY5k+w==",
                            SecurityStamp = "9eb901e4-7f0c-4c15-8317-b93f35c0487f",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "50ad756f-75a4-42ac-a9c2-287301f4b518",
                            ConcurrencyStamp = "3d555e45-c28e-43a1-a248-9f72b24b9a10",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAEKOGxTmQ6f6yaCu4eOSt2X87Ccb+lQh9ayPqOF5+j7MPnHsRcW2kueGsJYDoW7h7jQ==",
                            SecurityStamp = "73a2a3df-21c0-41cf-924b-2ee92c3d0cec",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "10744729-d70f-45dc-bfa9-6427490d32ce",
                            ConcurrencyStamp = "54f938b9-ce87-4871-b821-8af432942fa8",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAECUd6wRxES3wmhWf4vrdpTJj1V9jEEeqAHqK7QWZIO94d8FcOqz51bT+Rbl0Q9/qlA==",
                            SecurityStamp = "338fcc9c-27b6-4ddc-9f21-8ed0eccdb494",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "890dffd4-2c28-4cac-a353-833fb3d2be6a",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "2c4a1f4c-8648-476f-b25a-4df76b7439c3",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "d97f7cf0-9802-452f-9e9e-e2aa6db17e44",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7b245aad-b578-4301-8087-1ea820e39562",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "ca3606ca-ab04-47dc-9004-18fb129fe813",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "e76f1d06-a5be-4000-aa0e-53e0cbee6b13",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "418ebbc6-a571-4b16-bddb-3e10c85a94a0",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "da3962a7-8c95-47e3-9fba-460090c2205c",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3753947d-e359-443d-b5b9-e01636c8b306",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "76fff0d3-0dfb-44ed-92ff-5fa88274efb7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "71370e19-12e7-427d-a2cc-02bec1b032a0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "82678257-b20a-4ee8-8a8f-af9ab8d197d4",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "40e5148f-fa0b-4d0b-a998-d8ae7b46c2e8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "bfc1e140-3bf5-4b88-83e4-c9c8818edd29",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e32878cb-895b-4f7e-be8b-24bffbb0908b",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "924692db-40ba-4c40-bb30-9e2df2a31ba7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8c4e6128-4c38-4a55-a37b-7d6df6ce0450",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e56960b3-1ea4-49b2-91e4-e97b3d674370",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "47e0fcda-58c0-4590-964c-dae179f92932",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f5e404c4-33c8-44e7-9334-49eb7fc18b2d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d28b7523-bf79-43a3-b00b-cfbcad195925",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "0dbd5552-6f1f-4d82-881c-f22d85c2789b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d791bf20-7fce-4950-9355-f79812bd56fd",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "82b00941-53b0-43e8-be9b-d499f99422df",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "06b8a530-99ed-43e0-868d-e61bddb70fad",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "914d74f3-e00f-4832-bbfc-a1a8fa197dd5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8b3b6a36-740b-4ff4-90a2-68f4d648268f",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "5e469dbc-cb73-468d-96f6-08775e3b914f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ddad886a-0374-4216-8a0e-44b97d9415b6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "ce329555-f617-4932-8612-35aa95ae7b73",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "789e8ba5-d2a7-474c-9388-709f8d555444",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "01e39ff9-7d2c-4adc-af9a-1def1731f356",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "71873536-d293-4abe-b1a8-c3e3409e4419",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "6f45e132-0852-4469-abfb-44a8310901ec",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "36848f24-c34a-4b47-a978-019a7edf5916",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d3bed2dd-fc8a-4d79-8c55-fa719ae3d50c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "1f8ce4af-5006-4286-a3a6-2afe3afcdfaf",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "27b82b23-1b44-4109-b67e-436096e44aed",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0c514623-a8dd-4596-a8bb-44aa2cedff5d",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "e433d64a-67b7-41bf-a601-b0699aa8b919",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d3c43796-5ef4-4ffe-937e-5ba4c5a8482b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b380b92c-3735-479f-9ac9-ff009e753037",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5441893b-7bca-418d-870d-fbe7eb16bfe2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5f86318f-6981-4378-b202-b0323193f477",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d1062501-1fa7-432a-8580-4c338adcdab2",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "a38c9770-bc32-4740-bcea-ee0f6881e0d8",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a7ac7ab2-ed5b-4bc4-9e3e-a1df13c1992f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "67915455-ec4a-4f16-9de9-85f70f49a244",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5d6426fb-2a54-4baa-9ed2-507ae47c71f6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f69a9979-f663-4757-9892-7bea2980908c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a640a904-76b0-4b68-9c94-1e9881c14efb",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "50ad756f-75a4-42ac-a9c2-287301f4b518",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "10744729-d70f-45dc-bfa9-6427490d32ce",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanManagementCapital.Data.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HumanCapitalManagement.Data.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanManagementCapital.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanManagementCapital.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanManagementCapital.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanManagementCapital.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
