// <auto-generated />
using System;
using HumanCapitalManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCapitalManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanCapitalManagement.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "807ffea6-a378-4b09-90c3-cbc53690a228",
                            ConcurrencyStamp = "bcc8f8db-2b4c-430c-af42-5b07034211ce",
                            Email = "johndoe1@personal.gmail",
                            NormalizedEmail = "JOHNDOE1@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE1",
                            PasswordHash = "AQAAAAIAAYagAAAAEPiCod0nY8YMD1me8IYwaFXhMbznd6ViK8kb/yEDiWh+G6l+z1EOgcX8F0bAwFT/UA==",
                            SecurityStamp = "0db7654b-c8c1-489c-9795-34bc30256721",
                            UserName = "JohnDoe1"
                        },
                        new
                        {
                            Id = "e1569033-d81c-467c-b249-e8bb3e16100e",
                            ConcurrencyStamp = "cbc14b9b-2efd-4218-9f9f-b724a202f274",
                            Email = "johndoe2@personal.gmail",
                            NormalizedEmail = "JOHNDOE2@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE2",
                            PasswordHash = "AQAAAAIAAYagAAAAEKLprRwDl98ONZv7nQT8OJx2E52rMVQ/6LqQX4YKrJB7rOTCev+vaxEH6ywX7+dFQQ==",
                            SecurityStamp = "a9276a60-6f7c-4b82-bec7-aa7bd23d2596",
                            UserName = "JohnDoe2"
                        },
                        new
                        {
                            Id = "f0a80dde-96fe-4611-9bee-44ca68cfba4c",
                            ConcurrencyStamp = "ca5da5d0-9c7c-4159-b0b1-f67d687b1cea",
                            Email = "johndoe3@personal.gmail",
                            NormalizedEmail = "JOHNDOE3@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE3",
                            PasswordHash = "AQAAAAIAAYagAAAAEKoj1f2/WIDdae18R93lBByL5hEtfMzezz2+373xrmq4XLDvYN618pkxHzDGYHYc/w==",
                            SecurityStamp = "00a57427-df0c-4773-b134-046a079f2468",
                            UserName = "JohnDoe3"
                        },
                        new
                        {
                            Id = "231bbd41-d41b-408a-82af-7f9c09aedadd",
                            ConcurrencyStamp = "b13a4219-8bd4-4f89-8c5d-49b7dc47d3b3",
                            Email = "johndoe4@personal.gmail",
                            NormalizedEmail = "JOHNDOE4@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE4",
                            PasswordHash = "AQAAAAIAAYagAAAAEPR06EAbJ80MdMaNiuEAyZEyCowKoNA5l60p4fB06VNDg/eVuWaGNUHVO5ORyjCiQA==",
                            SecurityStamp = "53258e01-cf7f-404e-99a1-50e9eedf1fe6",
                            UserName = "JohnDoe4"
                        },
                        new
                        {
                            Id = "7827929f-837c-4c79-9aa6-6a025f9309c8",
                            ConcurrencyStamp = "29b96cd1-b080-459d-bc1c-c3ecea54b486",
                            Email = "johndoe5@personal.gmail",
                            NormalizedEmail = "JOHNDOE5@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE5",
                            PasswordHash = "AQAAAAIAAYagAAAAED95jy1zRYz+5xmO3pvl5RGHZH9BG7TmwBzpydi65QiBA53j7cazJCGEpd+DY64KTQ==",
                            SecurityStamp = "56e57cf1-294c-4668-8556-ee5eef56bf2a",
                            UserName = "JohnDoe5"
                        },
                        new
                        {
                            Id = "385e6370-3ae5-465e-bd9d-d13902f11c83",
                            ConcurrencyStamp = "3493f3de-e7bf-4e43-96e6-db42c4a654f4",
                            Email = "johndoe6@personal.gmail",
                            NormalizedEmail = "JOHNDOE6@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE6",
                            PasswordHash = "AQAAAAIAAYagAAAAEDnLYBkxjvjFo69Za8Lv/IKAnLUPJ9amK7MyYi8psPB8siCAKKR9sqjMWLRqlIw+SQ==",
                            SecurityStamp = "1959f1a1-ba09-403c-b533-a7ff95fce2d4",
                            UserName = "JohnDoe6"
                        },
                        new
                        {
                            Id = "38292939-4e0e-4d33-b8c9-aa99b6c033be",
                            ConcurrencyStamp = "3598ca6d-1b5d-44f2-98ec-3001163f986a",
                            Email = "johndoe7@personal.gmail",
                            NormalizedEmail = "JOHNDOE7@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE7",
                            PasswordHash = "AQAAAAIAAYagAAAAEEYIwQBY5uISo0cPzelGHR5NwBFms6ScqW8tfpzvWOuKGiMsdux6QX+yFpeaioeNyQ==",
                            SecurityStamp = "a888635c-2661-4cb1-85c2-5b3b4a7d6f9a",
                            UserName = "JohnDoe7"
                        },
                        new
                        {
                            Id = "6a21b06b-55ea-42b4-a104-90089134e536",
                            ConcurrencyStamp = "4286a1b2-c10b-4dce-84b0-193ea1745727",
                            Email = "johndoe8@personal.gmail",
                            NormalizedEmail = "JOHNDOE8@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE8",
                            PasswordHash = "AQAAAAIAAYagAAAAELcJr2qgcgxp720JoqHGCwjpYFsR2m6/wIvFUgalmBrNqB9ZbO5Bzwhi2qJBpJKRLg==",
                            SecurityStamp = "bc776a81-2278-4ffd-a3b8-aa6d2fac8cf6",
                            UserName = "JohnDoe8"
                        },
                        new
                        {
                            Id = "7c7d1d58-5431-4628-95a4-65b25a10f771",
                            ConcurrencyStamp = "829cdaf7-010e-42ff-b50b-b7c0fe4dcca2",
                            Email = "johndoe9@personal.gmail",
                            NormalizedEmail = "JOHNDOE9@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE9",
                            PasswordHash = "AQAAAAIAAYagAAAAEGFHc7wwzTcpXu3XWxxGfj8m5VyMoYKauqN0pctI7hV9nRL5lrKDU7gDwuxoP6N0XQ==",
                            SecurityStamp = "dd9eb9ae-672e-4b89-9157-309f56c09eba",
                            UserName = "JohnDoe9"
                        },
                        new
                        {
                            Id = "4849c0a0-5253-46dc-b38c-a80744f6a224",
                            ConcurrencyStamp = "df327ab9-df0e-4e88-b7a7-734097976ad1",
                            Email = "johndoe10@personal.gmail",
                            NormalizedEmail = "JOHNDOE10@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE10",
                            PasswordHash = "AQAAAAIAAYagAAAAEJtKAVWHfflapqv+siVSAutvJi1SJIVU9ngqeg/6SYZWdogAthpLWMlovwAvmk2XUw==",
                            SecurityStamp = "ea0554f5-4254-424d-a813-36119d2be49c",
                            UserName = "JohnDoe10"
                        },
                        new
                        {
                            Id = "711d97ad-25c9-40b8-b079-fc9e8ef748a2",
                            ConcurrencyStamp = "124c29bd-c7c1-4cb5-a691-1f447e888026",
                            Email = "johndoe11@personal.gmail",
                            NormalizedEmail = "JOHNDOE11@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE11",
                            PasswordHash = "AQAAAAIAAYagAAAAEFmtpVMvjqUUO5IrBMEgxtSW05bglFVJw+rLDisDvoUHtfZYlT3osAiOL4mPqeSBbg==",
                            SecurityStamp = "f29eaa94-b804-4873-8980-dbc24d5ca32f",
                            UserName = "JohnDoe11"
                        },
                        new
                        {
                            Id = "889d02b1-8a37-43f5-94b8-feb07a4489bc",
                            ConcurrencyStamp = "963ec5c3-c41f-4968-80bb-c7f0bbc11af9",
                            Email = "johndoe12@personal.gmail",
                            NormalizedEmail = "JOHNDOE12@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE12",
                            PasswordHash = "AQAAAAIAAYagAAAAEFzYd7dA/NQgutZPQFNFw1PsFNHXUshudE2zGIqyv/As8CKA3Y8+FjFCToOpNKVJWA==",
                            SecurityStamp = "5cdc2a50-7671-4a36-9b03-dade0504463b",
                            UserName = "JohnDoe12"
                        },
                        new
                        {
                            Id = "8177d6ef-90c9-4690-b3e8-bc5971204277",
                            ConcurrencyStamp = "d8ed011e-00bf-4f8e-989e-5eaa359985a1",
                            Email = "johndoe13@personal.gmail",
                            NormalizedEmail = "JOHNDOE13@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE13",
                            PasswordHash = "AQAAAAIAAYagAAAAEEWKCNLB2c1uYLaeV3wDhaJh/+9nWwxR19U9QYqi9/tb+EnFbHKGNNQAVvhnn3UOKA==",
                            SecurityStamp = "97154a62-30ae-42c9-a9f1-5aa4cb1d2a7e",
                            UserName = "JohnDoe13"
                        },
                        new
                        {
                            Id = "2d4eb86b-684f-45e4-b4d7-c9716449878b",
                            ConcurrencyStamp = "9a30467e-ae72-48ca-b46d-9ee69316c91c",
                            Email = "johndoe14@personal.gmail",
                            NormalizedEmail = "JOHNDOE14@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE14",
                            PasswordHash = "AQAAAAIAAYagAAAAEK7+cQ+eZQOHQIJvRv9c8hWVTXm1fKhF182cEjPpRG6P6bOy/j4hrcIBVs3kjJSMBA==",
                            SecurityStamp = "dcd0c91b-dfd3-41c4-b680-febb393e149f",
                            UserName = "JohnDoe14"
                        },
                        new
                        {
                            Id = "15620d8e-12da-41a7-80ee-6671ad4a0433",
                            ConcurrencyStamp = "57d15120-3e07-4457-9fed-b2ca09e78787",
                            Email = "johndoe15@personal.gmail",
                            NormalizedEmail = "JOHNDOE15@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE15",
                            PasswordHash = "AQAAAAIAAYagAAAAEKs3kdzSqFXfsjDL9mUNxHR0Cd9I0RDSG/E94aZijG4Mm1EQMBohdxSvP8eMQars1Q==",
                            SecurityStamp = "93af864a-9a9f-49c6-a28a-94e35c7755e4",
                            UserName = "JohnDoe15"
                        },
                        new
                        {
                            Id = "fe76c706-6f52-49c4-820f-6d378710df2f",
                            ConcurrencyStamp = "2ae73e95-060f-4a5c-898b-fb32f86a4657",
                            Email = "johndoe16@personal.gmail",
                            NormalizedEmail = "JOHNDOE16@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE16",
                            PasswordHash = "AQAAAAIAAYagAAAAEDRbk84HY4SRs3SGMykVT3RydTTZu4z4MqyXXaxF0UHSNRJZw8rfhmnaPC2OdPBakw==",
                            SecurityStamp = "559e7ffb-4c1e-4b7b-8c63-a6e0f0b6fcfe",
                            UserName = "JohnDoe16"
                        },
                        new
                        {
                            Id = "eff03be9-2eda-4304-948c-55fc3d65a457",
                            ConcurrencyStamp = "62741722-86da-4e2e-9eb3-f22922528408",
                            Email = "johndoe17@personal.gmail",
                            NormalizedEmail = "JOHNDOE17@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE17",
                            PasswordHash = "AQAAAAIAAYagAAAAEJzbnzqphxm3GW3fct3Ze7nMynakYD4q2n0wI7cJkLBksveKQt99Hp6Grk1l4qVMkw==",
                            SecurityStamp = "39a4a8d7-3821-482f-ad38-83829add921a",
                            UserName = "JohnDoe17"
                        },
                        new
                        {
                            Id = "543d1a57-fd27-4089-8f92-83016b397cde",
                            ConcurrencyStamp = "dda3ae5e-e061-4055-a07d-e9a1dc2d0f0c",
                            Email = "johndoe18@personal.gmail",
                            NormalizedEmail = "JOHNDOE18@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE18",
                            PasswordHash = "AQAAAAIAAYagAAAAEPkYBVtCW/P+kETSSjo7hAZqMSE0hYiF9e6LYtRH/cOCAb1j3C5EWAEKb7trFD0Drw==",
                            SecurityStamp = "ceef723d-8c4e-4d42-b6d0-fae6c876b30b",
                            UserName = "JohnDoe18"
                        },
                        new
                        {
                            Id = "3bfd2e43-16ea-4d3e-a8cf-cc83bd9169cd",
                            ConcurrencyStamp = "5ef9e99f-45ed-417e-bac4-6b50d11c36ee",
                            Email = "johndoe19@personal.gmail",
                            NormalizedEmail = "JOHNDOE19@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE19",
                            PasswordHash = "AQAAAAIAAYagAAAAENSdr+kLG7CHejytHr1guzj3I6OFgmuHXnPF8/hDdziulOMgO8koH3w+rGvXTPOISQ==",
                            SecurityStamp = "fe2638d8-5dc7-42f1-a5bf-49a4a8b80254",
                            UserName = "JohnDoe19"
                        },
                        new
                        {
                            Id = "e5d87954-c9ce-496b-a84f-79dd729ea29e",
                            ConcurrencyStamp = "6cdb3d33-77e5-43c6-b6cb-236c68db3825",
                            Email = "johndoe20@personal.gmail",
                            NormalizedEmail = "JOHNDOE20@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE20",
                            PasswordHash = "AQAAAAIAAYagAAAAEM+qBo8xvgcexbrUA46ZsRe0QqKp1VM7cLgSnrnrPWztTHcHHA9h1oAVkK8bzsHuVg==",
                            SecurityStamp = "3d6f8e61-4b23-4b46-b9f7-43cdfaed4fc4",
                            UserName = "JohnDoe20"
                        },
                        new
                        {
                            Id = "8ccba1c0-b8b3-4d13-abf7-ffaa356f9c28",
                            ConcurrencyStamp = "d277cbdb-4cfc-4d00-b8d7-bdfe69bdc071",
                            Email = "johndoe21@personal.gmail",
                            NormalizedEmail = "JOHNDOE21@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE21",
                            PasswordHash = "AQAAAAIAAYagAAAAEF7wZ6WSsjy6q5SgCUWXQwju50TIuQAaaOhV2a1YrHfp6KPlRbdlbsPAoSUo03Osog==",
                            SecurityStamp = "85d7171f-412f-4d33-bb01-1422b43255c2",
                            UserName = "JohnDoe21"
                        },
                        new
                        {
                            Id = "5784b99e-69e3-4f8d-9217-c3cd1b4f4145",
                            ConcurrencyStamp = "8c894027-cdee-4df7-88e5-5ce07a67ad8a",
                            Email = "johndoe22@personal.gmail",
                            NormalizedEmail = "JOHNDOE22@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE22",
                            PasswordHash = "AQAAAAIAAYagAAAAEI1XcFpGU9LYuNSr1YMPTl+pGNxzInavFR6QmETe7RnKP4I9J7K5LNytY61BtS2uBw==",
                            SecurityStamp = "a5a0c907-91b3-4df3-8634-c8f22c28eb30",
                            UserName = "JohnDoe22"
                        },
                        new
                        {
                            Id = "0573bbba-a926-4845-a28d-b59dbee8e7a9",
                            ConcurrencyStamp = "9f6a9e43-a7a8-4e33-8379-464b1953f547",
                            Email = "johndoe23@personal.gmail",
                            NormalizedEmail = "JOHNDOE23@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE23",
                            PasswordHash = "AQAAAAIAAYagAAAAEHCSNSJVggiXi4SOTlX63jJjxgiSSSq2ORwdoedGgmNxZM2JMRoVkyXTr6q1ZgD2RQ==",
                            SecurityStamp = "bcfc07a3-a033-4176-8633-f9dec24b69bb",
                            UserName = "JohnDoe23"
                        },
                        new
                        {
                            Id = "48a9ec2b-37c5-4483-988f-28956c4c8bc7",
                            ConcurrencyStamp = "21878c8b-7d59-4741-a0cb-e05fa3a7d208",
                            Email = "johndoe24@personal.gmail",
                            NormalizedEmail = "JOHNDOE24@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE24",
                            PasswordHash = "AQAAAAIAAYagAAAAEI2OaRStfjKKbrocDqKwXlBlv9r65Rf+HzDZJ8W9sUbjfUKbRXrUt4J0zLfglk1ZFg==",
                            SecurityStamp = "bc640612-444d-4369-b5d0-e065dc360403",
                            UserName = "JohnDoe24"
                        },
                        new
                        {
                            Id = "870fdb1b-aaa0-4df2-828b-c2b51af111e1",
                            ConcurrencyStamp = "8e7c316c-598d-4115-bc3b-b85824607594",
                            Email = "johndoe25@personal.gmail",
                            NormalizedEmail = "JOHNDOE25@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE25",
                            PasswordHash = "AQAAAAIAAYagAAAAEACS4B2H63YvMkh1VNMfpMkziaLX2Uxq/x3mrkR47VT/XFxwMkmZIPLpA3xkuc6Ufw==",
                            SecurityStamp = "7cac8d02-9c97-4dd5-87fb-a318b757243c",
                            UserName = "JohnDoe25"
                        },
                        new
                        {
                            Id = "870bc4c6-8719-4c65-9f1a-605762ec5f5c",
                            ConcurrencyStamp = "cf39c3ea-b3e7-40a5-b10e-3520365a321e",
                            Email = "johndoe26@personal.gmail",
                            NormalizedEmail = "JOHNDOE26@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE26",
                            PasswordHash = "AQAAAAIAAYagAAAAEMN0i5ee/pDWg2Hf6IA7ETnYFNFxAWuRIZXjQe5I5eWMZFgeWIPgsBmdzMxjLUVF+A==",
                            SecurityStamp = "5c8f4a12-d5c6-4067-b647-02cb82a339ad",
                            UserName = "JohnDoe26"
                        },
                        new
                        {
                            Id = "0bc32a8f-fadb-4f16-85f6-acfb652c7762",
                            ConcurrencyStamp = "7fdec769-2d04-4e6c-83af-77bcb6e0bab8",
                            Email = "johndoe27@personal.gmail",
                            NormalizedEmail = "JOHNDOE27@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE27",
                            PasswordHash = "AQAAAAIAAYagAAAAEFsN/1CoGrBObiViseFV7e6CYZpqe0MbEHAWRGHgG6Bicdaiv15c5UY+emjE5sjvbg==",
                            SecurityStamp = "86fa7f06-f61c-45e2-bb02-ead0a599c4eb",
                            UserName = "JohnDoe27"
                        },
                        new
                        {
                            Id = "f3f22722-2561-45a8-8602-99d3d7c08c4c",
                            ConcurrencyStamp = "4a94b657-0a0e-4492-b621-5d16fc4000c1",
                            Email = "johndoe28@personal.gmail",
                            NormalizedEmail = "JOHNDOE28@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE28",
                            PasswordHash = "AQAAAAIAAYagAAAAEIGraplLmRi9RhqNBz0BQf7C3rIRx5Q6sKDUzWln3N83rJ8s9XRiE74Ql+EyXBUilg==",
                            SecurityStamp = "c402b85a-d205-4190-9df5-e296c4e7ee3e",
                            UserName = "JohnDoe28"
                        },
                        new
                        {
                            Id = "56ced998-b75f-4d6e-bfd6-a681c2bb1bd9",
                            ConcurrencyStamp = "6071da45-9c18-4e73-9b08-03d262c34edb",
                            Email = "johndoe29@personal.gmail",
                            NormalizedEmail = "JOHNDOE29@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE29",
                            PasswordHash = "AQAAAAIAAYagAAAAED907A+ylV22kW2S03w7VEs++NamOWcJ+TfAzh1Mi0U22pUPGbf8AwvAigahtlU2Iw==",
                            SecurityStamp = "9b3565c4-d3b3-4781-9eae-8fe7d5e48002",
                            UserName = "JohnDoe29"
                        },
                        new
                        {
                            Id = "f20b371a-4a74-47b5-ac13-82faa4a003df",
                            ConcurrencyStamp = "284a1f51-63da-4567-9e96-8c5ed2515046",
                            Email = "johndoe30@personal.gmail",
                            NormalizedEmail = "JOHNDOE30@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE30",
                            PasswordHash = "AQAAAAIAAYagAAAAEHayHX/rwvnUX3NL7bw/28Id0P1gDqSG0guv3zL0WcZY7E7/gJQteyRu+NoCHEDGIw==",
                            SecurityStamp = "ca89c575-9e4a-4f32-83b1-2c6f5c884932",
                            UserName = "JohnDoe30"
                        },
                        new
                        {
                            Id = "6dd4a31c-08cb-4049-85fa-0c0d8e774b15",
                            ConcurrencyStamp = "f0198ca9-a2a7-4adc-9a79-803b1481ec7e",
                            Email = "johndoe31@personal.gmail",
                            NormalizedEmail = "JOHNDOE31@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE31",
                            PasswordHash = "AQAAAAIAAYagAAAAEKreJSTD/YUyuPLJ2m28Zn43j5/gxO4J2LAPEg08oFqRIOwvWcFzJcjN2N4St1knKQ==",
                            SecurityStamp = "27e4b9c7-8852-4bdf-b025-96828b65bad6",
                            UserName = "JohnDoe31"
                        },
                        new
                        {
                            Id = "2fb7807a-edaa-4cf2-b413-689279eff9e6",
                            ConcurrencyStamp = "b2460c60-e6ed-4012-aca8-8c7fb73c3cec",
                            Email = "johndoe32@personal.gmail",
                            NormalizedEmail = "JOHNDOE32@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE32",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBSQK7MJs4cO4nowSesBlKKLcl6gONyo8oWQsJIVeUk+NO45iGRD3yUr2qqO90sIA==",
                            SecurityStamp = "34495a9c-c65b-40f9-b1fe-35a9dfc8c084",
                            UserName = "JohnDoe32"
                        },
                        new
                        {
                            Id = "f54d0684-3e25-4c67-9950-ad6cc073f815",
                            ConcurrencyStamp = "eab4a3a0-cbc7-4838-ab27-a7855d5efc30",
                            Email = "johndoe33@personal.gmail",
                            NormalizedEmail = "JOHNDOE33@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE33",
                            PasswordHash = "AQAAAAIAAYagAAAAEIJyiLbflLMLS4/7z/KFm63dQhJOncBGFRiBndMxJ3glI+khE7eycYM84N+mI2YPVg==",
                            SecurityStamp = "334ab9ea-a379-4a28-b080-2e1781529ff0",
                            UserName = "JohnDoe33"
                        },
                        new
                        {
                            Id = "7e567655-fbca-47b2-b50d-a090d51b7e6e",
                            ConcurrencyStamp = "aa7d8f7d-f882-47fc-a06c-dcef86570584",
                            Email = "johndoe34@personal.gmail",
                            NormalizedEmail = "JOHNDOE34@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE34",
                            PasswordHash = "AQAAAAIAAYagAAAAEH5PUbMl3ePJKHPPhRkj8Ovy+imghqiZqyjMMpoNu3A9RIyDRJeMvdHX/SQEoHNYdA==",
                            SecurityStamp = "9f562078-084c-4bc3-a7b1-534935232cac",
                            UserName = "JohnDoe34"
                        },
                        new
                        {
                            Id = "66c314f2-e23c-401d-abca-931b1a9172a5",
                            ConcurrencyStamp = "ea535300-bc7d-4aed-af78-0af53591e0f0",
                            Email = "johndoe35@personal.gmail",
                            NormalizedEmail = "JOHNDOE35@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE35",
                            PasswordHash = "AQAAAAIAAYagAAAAEDF65tNITIeR+BIMfVkZnkdkD+/yY02m4Z4QSQdI3JKEpcUlbYoknnZSMOv2TeyNbQ==",
                            SecurityStamp = "2ae1e6ba-0df3-4da2-97df-1b385a5b3d9d",
                            UserName = "JohnDoe35"
                        },
                        new
                        {
                            Id = "3856ea67-c0ec-49f5-8562-b551b9f4b4b5",
                            ConcurrencyStamp = "e48ab97c-c66d-4b32-be47-51fe946c37f1",
                            Email = "johndoe36@personal.gmail",
                            NormalizedEmail = "JOHNDOE36@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE36",
                            PasswordHash = "AQAAAAIAAYagAAAAEODMq2uXBc29n20yDXdHfxLZ/2kqPz3HjKTBivPZ5dxMipEkUYOy4/MyjM3DocP0qA==",
                            SecurityStamp = "18115d65-35d8-4c93-b681-639154bb6b20",
                            UserName = "JohnDoe36"
                        },
                        new
                        {
                            Id = "e847fbe7-e9bd-4cae-9a1e-9e3c4577c6a6",
                            ConcurrencyStamp = "98c01e13-c450-4174-ab47-1883ba29de78",
                            Email = "johndoe37@personal.gmail",
                            NormalizedEmail = "JOHNDOE37@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE37",
                            PasswordHash = "AQAAAAIAAYagAAAAEI1iV+PbdTFKGKmJNx7A5RxgVq7rxN52KCN3CY6C7ZjgwsbZjkden6yjAMrXOmrSOg==",
                            SecurityStamp = "830e55a5-18ec-4a6d-a93e-f2032b591e98",
                            UserName = "JohnDoe37"
                        },
                        new
                        {
                            Id = "1fb73c13-9a3a-4ee8-ac12-3c45a235f491",
                            ConcurrencyStamp = "b5cd75c2-b81c-4a8d-9c72-f0edb4ef0114",
                            Email = "johndoe38@personal.gmail",
                            NormalizedEmail = "JOHNDOE38@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE38",
                            PasswordHash = "AQAAAAIAAYagAAAAEC5ys070NIM+D2B7Hi2XuPVKHPtN7PrcBh/XV+4F4M4d0hpv1621j+XOi8vjt1QTOg==",
                            SecurityStamp = "f3d91211-95bd-4206-b083-890d5bc551e6",
                            UserName = "JohnDoe38"
                        },
                        new
                        {
                            Id = "955f6510-121c-4da4-b3cc-be5a76ef0136",
                            ConcurrencyStamp = "b3b79e8f-2469-45bf-97b3-fd823269c9b8",
                            Email = "johndoe39@personal.gmail",
                            NormalizedEmail = "JOHNDOE39@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE39",
                            PasswordHash = "AQAAAAIAAYagAAAAEJEWWsXWgy7j7DJ/jqfgSrmLlbSSo3goOEbJmJt3XKuyKAP5JaDrrnP4s1EbGgoMNg==",
                            SecurityStamp = "539c706f-5c24-46ff-aae1-8eb3ac03f1cd",
                            UserName = "JohnDoe39"
                        },
                        new
                        {
                            Id = "843ccd29-f525-43cf-a621-94c32a04e3e2",
                            ConcurrencyStamp = "13ae5aeb-0202-4450-bc17-2da338e70712",
                            Email = "johndoe40@personal.gmail",
                            NormalizedEmail = "JOHNDOE40@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE40",
                            PasswordHash = "AQAAAAIAAYagAAAAEPRwdg/EnCW3jeVCzubfZeHipTStV9arcuydEX0t+dMmQJTrcJ2MpLoVL0SApByhMA==",
                            SecurityStamp = "ef76bc2f-a619-4412-8a9e-104177801f80",
                            UserName = "JohnDoe40"
                        },
                        new
                        {
                            Id = "2ade2183-5269-451d-9f68-1450770ee6e0",
                            ConcurrencyStamp = "78bf7962-7715-43d6-98ed-54f22b85be8a",
                            Email = "johndoe41@personal.gmail",
                            NormalizedEmail = "JOHNDOE41@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE41",
                            PasswordHash = "AQAAAAIAAYagAAAAEKUO3AprbmokGsJ/Ik1a1ETbiDUc6lSjgIvPI98/vkid4SG3oRoW9pxnctw2PC0Bxg==",
                            SecurityStamp = "cbdd5342-1874-4bdc-ad12-f60cd1c6acba",
                            UserName = "JohnDoe41"
                        },
                        new
                        {
                            Id = "dee346c3-0e66-4762-b2f4-4c6cbb72f53f",
                            ConcurrencyStamp = "a8057408-a49b-4dcf-94f4-5c1f9fc8a082",
                            Email = "johndoe42@personal.gmail",
                            NormalizedEmail = "JOHNDOE42@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE42",
                            PasswordHash = "AQAAAAIAAYagAAAAEP/4W240XUL1lN1QhiLPp02B6hnmBxxbsy1kQrl0qGLHuodyqfoD3QJSa70vY6GczQ==",
                            SecurityStamp = "ae0561d9-668f-4a6a-97f3-1365d7a8b495",
                            UserName = "JohnDoe42"
                        },
                        new
                        {
                            Id = "885218c8-80f6-4906-8357-e231f6f5272f",
                            ConcurrencyStamp = "b679a567-ef50-4c3a-b119-85c37a63802e",
                            Email = "johndoe43@personal.gmail",
                            NormalizedEmail = "JOHNDOE43@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE43",
                            PasswordHash = "AQAAAAIAAYagAAAAEC13RTjxzvFEf/4giNKwbIfhM/Li90uXtUe7kvmx9DLolo6kcrb4/gMZuSl+cnXMnA==",
                            SecurityStamp = "56f7174d-ef8a-4d18-8b11-966aadc78843",
                            UserName = "JohnDoe43"
                        },
                        new
                        {
                            Id = "71b4e51e-f700-4c24-a9cc-65235cca927b",
                            ConcurrencyStamp = "638d0407-0b3c-48dc-af5a-45c3e4abbf0b",
                            Email = "johndoe44@personal.gmail",
                            NormalizedEmail = "JOHNDOE44@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE44",
                            PasswordHash = "AQAAAAIAAYagAAAAECejzd7X1Wt0bkbC0O1sH3hEM0G4hJ6kmZt0kxucT5488Fe4aFtINu0qGZdC+gAEjQ==",
                            SecurityStamp = "ae927f7a-f973-4899-8cda-b3dd3cddef9d",
                            UserName = "JohnDoe44"
                        },
                        new
                        {
                            Id = "d1348522-6107-4ed5-824b-f30a3709aa04",
                            ConcurrencyStamp = "32ff7d09-170b-44fe-a888-fe68b6776926",
                            Email = "johndoe45@personal.gmail",
                            NormalizedEmail = "JOHNDOE45@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE45",
                            PasswordHash = "AQAAAAIAAYagAAAAEP2B3UJKmC35f5QLTwAme4K5otfJx4YktCZJ2x6TmU7THx7TE5qKwt5RRFq/BXug9w==",
                            SecurityStamp = "166ff630-2c71-438d-999d-691f11591f89",
                            UserName = "JohnDoe45"
                        },
                        new
                        {
                            Id = "e0a31994-45f5-4924-949b-4288b7a87f8d",
                            ConcurrencyStamp = "4d968c34-4750-45d5-bbe2-edc9c8d14e19",
                            Email = "johndoe46@personal.gmail",
                            NormalizedEmail = "JOHNDOE46@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE46",
                            PasswordHash = "AQAAAAIAAYagAAAAEBwxY+714enMI8Ru6EyWvVrGtHlgJ0MMNJ6ZVJINuhNDBD4FEQb5zNOkiEjs3Kn3WA==",
                            SecurityStamp = "e8570cc1-e449-4829-b59b-77b278e5cb4f",
                            UserName = "JohnDoe46"
                        },
                        new
                        {
                            Id = "b5bae1b5-4e8f-4fb4-a018-0fe283a46e59",
                            ConcurrencyStamp = "2b6d8b93-11b1-4cca-b65d-b1ed31f443b6",
                            Email = "johndoe47@personal.gmail",
                            NormalizedEmail = "JOHNDOE47@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE47",
                            PasswordHash = "AQAAAAIAAYagAAAAEMZhEV8okkJRuq4gybGDhF/i1nkP05scPKgQ520zAv1yO47fnvXwFuAXNcTIv3L5gg==",
                            SecurityStamp = "ce3679d5-cf2e-4d3c-abaa-4866f3e0de83",
                            UserName = "JohnDoe47"
                        },
                        new
                        {
                            Id = "bb0e0279-3a6c-4dab-86f6-f3d90cb2b3e4",
                            ConcurrencyStamp = "32962d5a-3a3e-46c9-90e4-ac8c9aadd1c4",
                            Email = "johndoe48@personal.gmail",
                            NormalizedEmail = "JOHNDOE48@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE48",
                            PasswordHash = "AQAAAAIAAYagAAAAEFfghMXhEHnh+YmWFBcstiQcn6C7MdFwHluo7l5n5zF/LA/qyyzpNj9q/jeP7ED+nw==",
                            SecurityStamp = "fe094606-04d9-46cf-a8b5-cbf0c25ca0d9",
                            UserName = "JohnDoe48"
                        },
                        new
                        {
                            Id = "97007bfd-66be-4585-9de1-3201e8ed912b",
                            ConcurrencyStamp = "64847704-cea1-478b-ad0f-28e86c988205",
                            Email = "johndoe49@personal.gmail",
                            NormalizedEmail = "JOHNDOE49@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE49",
                            PasswordHash = "AQAAAAIAAYagAAAAEDihdeP/MFSDyxBGAWqvQK4fdVbDAWZq0TOY21X6jC3S0SydJu1koD2XS+8Lp3Ggmw==",
                            SecurityStamp = "3821dd79-2579-42ca-8a69-0ef8549ad20a",
                            UserName = "JohnDoe49"
                        },
                        new
                        {
                            Id = "9fa4fd2a-2fe1-4e35-9060-0bb66c8d6c01",
                            ConcurrencyStamp = "fe8ef65f-2af7-44ce-90f6-a144b0f31894",
                            Email = "johndoe50@personal.gmail",
                            NormalizedEmail = "JOHNDOE50@PERSONAL.GMAIL",
                            NormalizedUserName = "JOHNDOE50",
                            PasswordHash = "AQAAAAIAAYagAAAAEFFOuGSumBdWUpYT/+VS1QnCl2/d9YlZ09ZjonpUG1CUJwvuhzUUCnyiXFOMmphBWA==",
                            SecurityStamp = "6fea90f9-5832-4266-8003-79a391d2bb32",
                            UserName = "JohnDoe50"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Operations"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EncryptedIBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "johndoe1@company.gmail",
                            Country = "France",
                            DepartmentId = 2,
                            EncryptedIBAN = "RlI2NDMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Finance Manager",
                            LastName = "Doe",
                            Salary = 3012.0m,
                            UserId = "807ffea6-a378-4b09-90c3-cbc53690a228"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "johndoe2@company.gmail",
                            Country = "France",
                            DepartmentId = 3,
                            EncryptedIBAN = "RlI1MTMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "IT Manager",
                            LastName = "Doe",
                            Salary = 7389.0m,
                            UserId = "e1569033-d81c-467c-b249-e8bb3e16100e"
                        },
                        new
                        {
                            Id = 3,
                            CompanyEmail = "johndoe3@company.gmail",
                            Country = "Britain",
                            DepartmentId = 4,
                            EncryptedIBAN = "R0IxNk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Marketing Manager",
                            LastName = "Doe",
                            Salary = 3055.5m,
                            UserId = "f0a80dde-96fe-4611-9bee-44ca68cfba4c"
                        },
                        new
                        {
                            Id = 4,
                            CompanyEmail = "johndoe4@company.gmail",
                            Country = "Britain",
                            DepartmentId = 5,
                            EncryptedIBAN = "R0IxMU5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Sales Manager",
                            LastName = "Doe",
                            Salary = 5010.0m,
                            UserId = "231bbd41-d41b-408a-82af-7f9c09aedadd"
                        },
                        new
                        {
                            Id = 5,
                            CompanyEmail = "johndoe5@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 6,
                            EncryptedIBAN = "Qkc2OVVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Operations Manager",
                            LastName = "Doe",
                            Salary = 4198.5m,
                            UserId = "7827929f-837c-4c79-9aa6-6a025f9309c8"
                        },
                        new
                        {
                            Id = 6,
                            CompanyEmail = "johndoe6@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 1,
                            EncryptedIBAN = "Qkc0M1VOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "HR Manager",
                            LastName = "Doe",
                            Salary = 2308.5m,
                            UserId = "385e6370-3ae5-465e-bd9d-d13902f11c83"
                        },
                        new
                        {
                            Id = 7,
                            CompanyEmail = "johndoe7@company.gmail",
                            Country = "France",
                            DepartmentId = 2,
                            EncryptedIBAN = "RlI2NzMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2096m,
                            UserId = "38292939-4e0e-4d33-b8c9-aa99b6c033be"
                        },
                        new
                        {
                            Id = 8,
                            CompanyEmail = "johndoe8@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 3,
                            EncryptedIBAN = "Qkc3OVVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "System Admin",
                            LastName = "Doe",
                            Salary = 4674m,
                            UserId = "6a21b06b-55ea-42b4-a104-90089134e536"
                        },
                        new
                        {
                            Id = 9,
                            CompanyEmail = "johndoe9@company.gmail",
                            Country = "Britain",
                            DepartmentId = 4,
                            EncryptedIBAN = "R0I3M05XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2109m,
                            UserId = "7c7d1d58-5431-4628-95a4-65b25a10f771"
                        },
                        new
                        {
                            Id = 10,
                            CompanyEmail = "johndoe10@company.gmail",
                            Country = "Britain",
                            DepartmentId = 5,
                            EncryptedIBAN = "R0I2Nk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 2320m,
                            UserId = "4849c0a0-5253-46dc-b38c-a80744f6a224"
                        },
                        new
                        {
                            Id = 11,
                            CompanyEmail = "johndoe11@company.gmail",
                            Country = "USA",
                            DepartmentId = 6,
                            EncryptedIBAN = "VVMzOEJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2876m,
                            UserId = "711d97ad-25c9-40b8-b079-fc9e8ef748a2"
                        },
                        new
                        {
                            Id = 12,
                            CompanyEmail = "johndoe12@company.gmail",
                            Country = "Britain",
                            DepartmentId = 1,
                            EncryptedIBAN = "R0I2N05XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1702m,
                            UserId = "889d02b1-8a37-43f5-94b8-feb07a4489bc"
                        },
                        new
                        {
                            Id = 13,
                            CompanyEmail = "johndoe13@company.gmail",
                            Country = "Britain",
                            DepartmentId = 2,
                            EncryptedIBAN = "R0I5NE5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2045m,
                            UserId = "8177d6ef-90c9-4690-b3e8-bc5971204277"
                        },
                        new
                        {
                            Id = 14,
                            CompanyEmail = "johndoe14@company.gmail",
                            Country = "USA",
                            DepartmentId = 3,
                            EncryptedIBAN = "VVM5MEJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4807m,
                            UserId = "2d4eb86b-684f-45e4-b4d7-c9716449878b"
                        },
                        new
                        {
                            Id = 15,
                            CompanyEmail = "johndoe15@company.gmail",
                            Country = "USA",
                            DepartmentId = 4,
                            EncryptedIBAN = "VVM2MEJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2095m,
                            UserId = "15620d8e-12da-41a7-80ee-6671ad4a0433"
                        },
                        new
                        {
                            Id = 16,
                            CompanyEmail = "johndoe16@company.gmail",
                            Country = "Germany",
                            DepartmentId = 5,
                            EncryptedIBAN = "REU5NTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Sales Engineer",
                            LastName = "Doe",
                            Salary = 2396m,
                            UserId = "fe76c706-6f52-49c4-820f-6d378710df2f"
                        },
                        new
                        {
                            Id = 17,
                            CompanyEmail = "johndoe17@company.gmail",
                            Country = "France",
                            DepartmentId = 6,
                            EncryptedIBAN = "RlI4MTMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2546m,
                            UserId = "eff03be9-2eda-4304-948c-55fc3d65a457"
                        },
                        new
                        {
                            Id = 18,
                            CompanyEmail = "johndoe18@company.gmail",
                            Country = "Germany",
                            DepartmentId = 1,
                            EncryptedIBAN = "REU1MTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1708m,
                            UserId = "543d1a57-fd27-4089-8f92-83016b397cde"
                        },
                        new
                        {
                            Id = 19,
                            CompanyEmail = "johndoe19@company.gmail",
                            Country = "Britain",
                            DepartmentId = 2,
                            EncryptedIBAN = "R0I4Nk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2156m,
                            UserId = "3bfd2e43-16ea-4d3e-a8cf-cc83bd9169cd"
                        },
                        new
                        {
                            Id = 20,
                            CompanyEmail = "johndoe20@company.gmail",
                            Country = "France",
                            DepartmentId = 3,
                            EncryptedIBAN = "RlI0ODMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4925m,
                            UserId = "e5d87954-c9ce-496b-a84f-79dd729ea29e"
                        },
                        new
                        {
                            Id = 21,
                            CompanyEmail = "johndoe21@company.gmail",
                            Country = "USA",
                            DepartmentId = 4,
                            EncryptedIBAN = "VVM4MUJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2066m,
                            UserId = "8ccba1c0-b8b3-4d13-abf7-ffaa356f9c28"
                        },
                        new
                        {
                            Id = 22,
                            CompanyEmail = "johndoe22@company.gmail",
                            Country = "France",
                            DepartmentId = 5,
                            EncryptedIBAN = "RlI4NDMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 3746m,
                            UserId = "5784b99e-69e3-4f8d-9217-c3cd1b4f4145"
                        },
                        new
                        {
                            Id = 23,
                            CompanyEmail = "johndoe23@company.gmail",
                            Country = "Britain",
                            DepartmentId = 6,
                            EncryptedIBAN = "R0I5OE5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2604m,
                            UserId = "0573bbba-a926-4845-a28d-b59dbee8e7a9"
                        },
                        new
                        {
                            Id = 24,
                            CompanyEmail = "johndoe24@company.gmail",
                            Country = "France",
                            DepartmentId = 1,
                            EncryptedIBAN = "RlI4OTMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1678m,
                            UserId = "48a9ec2b-37c5-4483-988f-28956c4c8bc7"
                        },
                        new
                        {
                            Id = 25,
                            CompanyEmail = "johndoe25@company.gmail",
                            Country = "Germany",
                            DepartmentId = 2,
                            EncryptedIBAN = "REU3OTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2085m,
                            UserId = "870fdb1b-aaa0-4df2-828b-c2b51af111e1"
                        },
                        new
                        {
                            Id = 26,
                            CompanyEmail = "johndoe26@company.gmail",
                            Country = "Germany",
                            DepartmentId = 3,
                            EncryptedIBAN = "REU0NjM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4017m,
                            UserId = "870bc4c6-8719-4c65-9f1a-605762ec5f5c"
                        },
                        new
                        {
                            Id = 27,
                            CompanyEmail = "johndoe27@company.gmail",
                            Country = "Germany",
                            DepartmentId = 4,
                            EncryptedIBAN = "REUxMzM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2144m,
                            UserId = "0bc32a8f-fadb-4f16-85f6-acfb652c7762"
                        },
                        new
                        {
                            Id = 28,
                            CompanyEmail = "johndoe28@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 5,
                            EncryptedIBAN = "Qkc3MFVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 4330m,
                            UserId = "f3f22722-2561-45a8-8602-99d3d7c08c4c"
                        },
                        new
                        {
                            Id = 29,
                            CompanyEmail = "johndoe29@company.gmail",
                            Country = "Britain",
                            DepartmentId = 6,
                            EncryptedIBAN = "R0I2Mk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2721m,
                            UserId = "56ced998-b75f-4d6e-bfd6-a681c2bb1bd9"
                        },
                        new
                        {
                            Id = 30,
                            CompanyEmail = "johndoe30@company.gmail",
                            Country = "Germany",
                            DepartmentId = 1,
                            EncryptedIBAN = "REU1OTM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1542m,
                            UserId = "f20b371a-4a74-47b5-ac13-82faa4a003df"
                        },
                        new
                        {
                            Id = 31,
                            CompanyEmail = "johndoe31@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 2,
                            EncryptedIBAN = "QkcxOFVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2048m,
                            UserId = "6dd4a31c-08cb-4049-85fa-0c0d8e774b15"
                        },
                        new
                        {
                            Id = 32,
                            CompanyEmail = "johndoe32@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 3,
                            EncryptedIBAN = "Qkc1OVVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4466m,
                            UserId = "2fb7807a-edaa-4cf2-b413-689279eff9e6"
                        },
                        new
                        {
                            Id = 33,
                            CompanyEmail = "johndoe33@company.gmail",
                            Country = "Germany",
                            DepartmentId = 4,
                            EncryptedIBAN = "REUxNjM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Marketing Specialist",
                            LastName = "Doe",
                            Salary = 2061m,
                            UserId = "f54d0684-3e25-4c67-9950-ad6cc073f815"
                        },
                        new
                        {
                            Id = 34,
                            CompanyEmail = "johndoe34@company.gmail",
                            Country = "France",
                            DepartmentId = 5,
                            EncryptedIBAN = "RlI4NzMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 2633m,
                            UserId = "7e567655-fbca-47b2-b50d-a090d51b7e6e"
                        },
                        new
                        {
                            Id = 35,
                            CompanyEmail = "johndoe35@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 6,
                            EncryptedIBAN = "Qkc5N1VOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Supply Chain Analyst",
                            LastName = "Doe",
                            Salary = 2624m,
                            UserId = "66c314f2-e23c-401d-abca-931b1a9172a5"
                        },
                        new
                        {
                            Id = 36,
                            CompanyEmail = "johndoe36@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 1,
                            EncryptedIBAN = "QkczM1VOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Recruiter",
                            LastName = "Doe",
                            Salary = 1742m,
                            UserId = "3856ea67-c0ec-49f5-8562-b551b9f4b4b5"
                        },
                        new
                        {
                            Id = 37,
                            CompanyEmail = "johndoe37@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 2,
                            EncryptedIBAN = "QkczM1VOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Accountant",
                            LastName = "Doe",
                            Salary = 2011m,
                            UserId = "e847fbe7-e9bd-4cae-9a1e-9e3c4577c6a6"
                        },
                        new
                        {
                            Id = 38,
                            CompanyEmail = "johndoe38@company.gmail",
                            Country = "USA",
                            DepartmentId = 3,
                            EncryptedIBAN = "VVM0NUJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Software Developer",
                            LastName = "Doe",
                            Salary = 4587m,
                            UserId = "1fb73c13-9a3a-4ee8-ac12-3c45a235f491"
                        },
                        new
                        {
                            Id = 39,
                            CompanyEmail = "johndoe39@company.gmail",
                            Country = "France",
                            DepartmentId = 4,
                            EncryptedIBAN = "RlI5NDMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2000m,
                            UserId = "955f6510-121c-4da4-b3cc-be5a76ef0136"
                        },
                        new
                        {
                            Id = 40,
                            CompanyEmail = "johndoe40@company.gmail",
                            Country = "France",
                            DepartmentId = 5,
                            EncryptedIBAN = "RlI3NTMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "Sales Representative",
                            LastName = "Doe",
                            Salary = 4956m,
                            UserId = "843ccd29-f525-43cf-a621-94c32a04e3e2"
                        },
                        new
                        {
                            Id = 41,
                            CompanyEmail = "johndoe41@company.gmail",
                            Country = "USA",
                            DepartmentId = 6,
                            EncryptedIBAN = "VVM4MkJPRkE5ODc2NTQzMjEw",
                            FirstName = "John",
                            JobTitle = "Facilities Manager",
                            LastName = "Doe",
                            Salary = 2993m,
                            UserId = "2ade2183-5269-451d-9f68-1450770ee6e0"
                        },
                        new
                        {
                            Id = 42,
                            CompanyEmail = "johndoe42@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 1,
                            EncryptedIBAN = "Qkc2NlVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Training Specialist",
                            LastName = "Doe",
                            Salary = 1715m,
                            UserId = "dee346c3-0e66-4762-b2f4-4c6cbb72f53f"
                        },
                        new
                        {
                            Id = 43,
                            CompanyEmail = "johndoe43@company.gmail",
                            Country = "Britain",
                            DepartmentId = 2,
                            EncryptedIBAN = "R0I0N05XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2198m,
                            UserId = "885218c8-80f6-4906-8357-e231f6f5272f"
                        },
                        new
                        {
                            Id = 44,
                            CompanyEmail = "johndoe44@company.gmail",
                            Country = "Britain",
                            DepartmentId = 3,
                            EncryptedIBAN = "R0I0OE5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Network Engineer",
                            LastName = "Doe",
                            Salary = 4953m,
                            UserId = "71b4e51e-f700-4c24-a9cc-65235cca927b"
                        },
                        new
                        {
                            Id = 45,
                            CompanyEmail = "johndoe45@company.gmail",
                            Country = "France",
                            DepartmentId = 4,
                            EncryptedIBAN = "RlI3OTMwMDA2MTIzNDU2Nzg5MDE4OQ==",
                            FirstName = "John",
                            JobTitle = "SEO Analyst",
                            LastName = "Doe",
                            Salary = 2024m,
                            UserId = "d1348522-6107-4ed5-824b-f30a3709aa04"
                        },
                        new
                        {
                            Id = 46,
                            CompanyEmail = "johndoe46@company.gmail",
                            Country = "Britain",
                            DepartmentId = 5,
                            EncryptedIBAN = "R0IxOE5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Business Developer",
                            LastName = "Doe",
                            Salary = 4183m,
                            UserId = "e0a31994-45f5-4924-949b-4288b7a87f8d"
                        },
                        new
                        {
                            Id = 47,
                            CompanyEmail = "johndoe47@company.gmail",
                            Country = "Germany",
                            DepartmentId = 6,
                            EncryptedIBAN = "REU0NjM3MDQwMDQ0MDUzMjAxMzAwMA==",
                            FirstName = "John",
                            JobTitle = "Logistics Coordinator",
                            LastName = "Doe",
                            Salary = 2691m,
                            UserId = "b5bae1b5-4e8f-4fb4-a018-0fe283a46e59"
                        },
                        new
                        {
                            Id = 48,
                            CompanyEmail = "johndoe48@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 1,
                            EncryptedIBAN = "Qkc0NVVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Compensation Analyst",
                            LastName = "Doe",
                            Salary = 1506m,
                            UserId = "bb0e0279-3a6c-4dab-86f6-f3d90cb2b3e4"
                        },
                        new
                        {
                            Id = 49,
                            CompanyEmail = "johndoe49@company.gmail",
                            Country = "Britain",
                            DepartmentId = 2,
                            EncryptedIBAN = "R0IxNk5XQks2MDE2MTMzMTkyNjgxOQ==",
                            FirstName = "John",
                            JobTitle = "Auditor",
                            LastName = "Doe",
                            Salary = 2117m,
                            UserId = "97007bfd-66be-4585-9de1-3201e8ed912b"
                        },
                        new
                        {
                            Id = 50,
                            CompanyEmail = "johndoe50@company.gmail",
                            Country = "Bulgaria",
                            DepartmentId = 3,
                            EncryptedIBAN = "QkcxMlVOQ1IxMjM0NTY3ODkw",
                            FirstName = "John",
                            JobTitle = "Database Admin",
                            LastName = "Doe",
                            Salary = 4553m,
                            UserId = "9fa4fd2a-2fe1-4e35-9060-0bb66c8d6c01"
                        });
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.SalaryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryRecords");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "f3a923c1-02e6-4931-b7b3-5238032f9155",
                            Name = "HR Admin",
                            NormalizedName = "HR ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "92e0c423-c842-496b-921b-2704ffc17550",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "f0524a52-48d3-4ff3-b945-6dc5980f62e8",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "807ffea6-a378-4b09-90c3-cbc53690a228",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "e1569033-d81c-467c-b249-e8bb3e16100e",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "f0a80dde-96fe-4611-9bee-44ca68cfba4c",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "231bbd41-d41b-408a-82af-7f9c09aedadd",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "7827929f-837c-4c79-9aa6-6a025f9309c8",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "385e6370-3ae5-465e-bd9d-d13902f11c83",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "38292939-4e0e-4d33-b8c9-aa99b6c033be",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "6a21b06b-55ea-42b4-a104-90089134e536",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7c7d1d58-5431-4628-95a4-65b25a10f771",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4849c0a0-5253-46dc-b38c-a80744f6a224",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "711d97ad-25c9-40b8-b079-fc9e8ef748a2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "889d02b1-8a37-43f5-94b8-feb07a4489bc",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "8177d6ef-90c9-4690-b3e8-bc5971204277",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2d4eb86b-684f-45e4-b4d7-c9716449878b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "15620d8e-12da-41a7-80ee-6671ad4a0433",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "fe76c706-6f52-49c4-820f-6d378710df2f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "eff03be9-2eda-4304-948c-55fc3d65a457",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "543d1a57-fd27-4089-8f92-83016b397cde",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "3bfd2e43-16ea-4d3e-a8cf-cc83bd9169cd",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e5d87954-c9ce-496b-a84f-79dd729ea29e",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8ccba1c0-b8b3-4d13-abf7-ffaa356f9c28",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "5784b99e-69e3-4f8d-9217-c3cd1b4f4145",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0573bbba-a926-4845-a28d-b59dbee8e7a9",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "48a9ec2b-37c5-4483-988f-28956c4c8bc7",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "870fdb1b-aaa0-4df2-828b-c2b51af111e1",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "870bc4c6-8719-4c65-9f1a-605762ec5f5c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "0bc32a8f-fadb-4f16-85f6-acfb652c7762",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f3f22722-2561-45a8-8602-99d3d7c08c4c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "56ced998-b75f-4d6e-bfd6-a681c2bb1bd9",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f20b371a-4a74-47b5-ac13-82faa4a003df",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "6dd4a31c-08cb-4049-85fa-0c0d8e774b15",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2fb7807a-edaa-4cf2-b413-689279eff9e6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "f54d0684-3e25-4c67-9950-ad6cc073f815",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7e567655-fbca-47b2-b50d-a090d51b7e6e",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "66c314f2-e23c-401d-abca-931b1a9172a5",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "3856ea67-c0ec-49f5-8562-b551b9f4b4b5",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "e847fbe7-e9bd-4cae-9a1e-9e3c4577c6a6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "1fb73c13-9a3a-4ee8-ac12-3c45a235f491",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "955f6510-121c-4da4-b3cc-be5a76ef0136",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "843ccd29-f525-43cf-a621-94c32a04e3e2",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "2ade2183-5269-451d-9f68-1450770ee6e0",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "dee346c3-0e66-4762-b2f4-4c6cbb72f53f",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "885218c8-80f6-4906-8357-e231f6f5272f",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "71b4e51e-f700-4c24-a9cc-65235cca927b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "d1348522-6107-4ed5-824b-f30a3709aa04",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "e0a31994-45f5-4924-949b-4288b7a87f8d",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b5bae1b5-4e8f-4fb4-a018-0fe283a46e59",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "bb0e0279-3a6c-4dab-86f6-f3d90cb2b3e4",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "97007bfd-66be-4585-9de1-3201e8ed912b",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "9fa4fd2a-2fe1-4e35-9060-0bb66c8d6c01",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("HumanCapitalManagement.Data.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.SalaryRecord", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.Models.Employee", "Employee")
                        .WithMany("SalaryRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HumanCapitalManagement.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HumanCapitalManagement.Data.Models.Employee", b =>
                {
                    b.Navigation("SalaryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
